export interface CoreDictEntry {
  word: string;
  reading: string;
  meanings: string[];
}

export const CORE1000_DICT: Record<string, CoreDictEntry> = {
  "周り": { word: "周り", reading: "まわり", meanings: ["circumference", "girth", "surroundings"] },
  "学校": { word: "学校", reading: "がっこう", meanings: ["school", "Gakkou", "School"] },
  "川": { word: "川", reading: "かわ", meanings: ["river", "stream", "River"] },
  "手": { word: "手", reading: "て", meanings: ["hand", "arm", "forepaw"] },
  "戸": { word: "戸", reading: "と", meanings: ["door (esp. Japanese-style)", "shutter", "window shutter"] },
  "メガネ": { word: "メガネ", reading: "メガネ", meanings: ["glasses", "eyeglasses", "spectacles"] },
  "煙草": { word: "煙草", reading: "タバコ", meanings: ["tobacco", "cigarette", "cigar"] },
  "赤": { word: "赤", reading: "あか", meanings: ["red", "crimson", "scarlet"] },
  "仕事": { word: "仕事", reading: "しごと", meanings: ["work", "job", "labor"] },
  "英語": { word: "英語", reading: "えいご", meanings: ["English (language)", "English language"] },
  "問題": { word: "問題", reading: "もんだい", meanings: ["question (e.g. on a test)", "problem", "problem (e.g. societal, political)"] },
  "部屋": { word: "部屋", reading: "へや", meanings: ["room", "chamber", "apartment"] },
  "子供": { word: "子供", reading: "こども", meanings: ["child", "children", "Child"] },
  "時間": { word: "時間", reading: "じかん", meanings: ["time", "hour", "period"] },
  "雨": { word: "雨", reading: "あめ", meanings: ["rain", "rainy day", "rainy weather"] },
  "先生": { word: "先生", reading: "せんせい", meanings: ["teacher", "instructor", "master"] },
  "年": { word: "年", reading: "とし", meanings: ["year", "age", "years"] },
  "手紙": { word: "手紙", reading: "てがみ", meanings: ["letter", "note", "Letter (message)"] },
  "電話": { word: "電話", reading: "でんわ", meanings: ["telephone call", "phone call", "telephone (device)"] },
  "水": { word: "水", reading: "みず", meanings: ["water (esp. cool or cold)", "fluid (esp. in an animal tissue)", "liquid"] },
  "病気": { word: "病気", reading: "びょうき", meanings: ["illness (usu. excluding minor ailments, e.g. common cold)", "disease", "sickness"] },
  "会社": { word: "会社", reading: "かいしゃ", meanings: ["company", "corporation", "firm"] },
  "結婚": { word: "結婚", reading: "けっこん", meanings: ["marriage", "Marriage"] },
  "言葉": { word: "言葉", reading: "ことば", meanings: ["language", "dialect", "word"] },
  "目": { word: "目", reading: "め", meanings: ["eye", "eyeball", "eyesight"] },
  "走る": { word: "走る", reading: "はしる", meanings: ["to run", "to run (of a vehicle)", "to drive"] },
  "名前": { word: "名前", reading: "なまえ", meanings: ["name", "given name", "first name"] },
  "旅行": { word: "旅行", reading: "りょこう", meanings: ["travel", "trip", "journey"] },
  "道": { word: "道", reading: "みち", meanings: ["road", "path", "street"] },
  "飛行機": { word: "飛行機", reading: "ひこうき", meanings: ["airplane", "aeroplane", "plane"] },
  "映画": { word: "映画", reading: "えいが", meanings: ["movie", "film", "motion picture"] },
  "音楽": { word: "音楽", reading: "おんがく", meanings: ["music", "Music"] },
  "木": { word: "木", reading: "き", meanings: ["tree", "shrub", "bush"] },
  "大学": { word: "大学", reading: "だいがく", meanings: ["university", "college", "former imperial university of Japan (established under the ritsuryō system for the training of government administrators)"] },
  "時計": { word: "時計", reading: "とけい", meanings: ["clock", "watch", "timepiece"] },
  "家族": { word: "家族", reading: "かぞく", meanings: ["family", "Family"] },
  "花": { word: "花", reading: "はな", meanings: ["flower", "blossom", "bloom"] },
  "猫": { word: "猫", reading: "ねこ", meanings: ["cat (esp. the domestic cat, Felis catus)", "feline", "shamisen"] },
  "毎日": { word: "毎日", reading: "まいにち", meanings: ["every day", "daily", "Every Single Day (band)"] },
  "宿題": { word: "宿題", reading: "しゅくだい", meanings: ["homework", "assignment", "pending issue"] },
  "雪": { word: "雪", reading: "ゆき", meanings: ["snow", "snowfall", "Snow"] },
  "山": { word: "山", reading: "やま", meanings: ["mountain", "hill", "mine"] },
  "窓": { word: "窓", reading: "まど", meanings: ["window", "Window"] },
  "動物": { word: "動物", reading: "どうぶつ", meanings: ["animal", "Animal"] },
  "夜": { word: "夜", reading: "よる", meanings: ["night", "evening", "dinner"] },
  "料理": { word: "料理", reading: "りょうり", meanings: ["cooking", "cookery", "cuisine"] },
  "夏": { word: "夏", reading: "なつ", meanings: ["summer", "Summer"] },
  "新聞": { word: "新聞", reading: "しんぶん", meanings: ["newspaper", "Newspaper"] },
  "公園": { word: "公園", reading: "こうえん", meanings: ["(public) park", "Park"] },
  "意味": { word: "意味", reading: "いみ", meanings: ["meaning", "significance", "sense"] },
  "自転車": { word: "自転車", reading: "じてんしゃ", meanings: ["bicycle", "bike", "Bicycle"] },
  "足": { word: "足", reading: "あし", meanings: ["foot", "paw", "arm (of an octopus, squid, etc.)"] },
  "電車": { word: "電車", reading: "でんしゃ", meanings: ["train", "electric train", "Electric multiple unit"] },
  "散歩": { word: "散歩", reading: "さんぽ", meanings: ["walk", "stroll", "Strolling"] },
  "声": { word: "声", reading: "こえ", meanings: ["voice", "singing (of a bird)", "chirping (of an insect)"] },
  "朝": { word: "朝", reading: "あさ", meanings: ["morning", "breakfast", "Morning"] },
  "歌": { word: "歌", reading: "うた", meanings: ["song", "singing", "classical Japanese poem (esp. tanka)"] },
  "靴": { word: "靴", reading: "くつ", meanings: ["shoe", "shoes", "boots"] },
  "箱": { word: "箱", reading: "はこ", meanings: ["box", "case", "chest"] },
  "机": { word: "机", reading: "つくえ", meanings: ["desk", "Desk"] },
  "帽子": { word: "帽子", reading: "ぼうし", meanings: ["hat", "cap", "cap (move)"] },
  "海": { word: "海", reading: "うみ", meanings: ["sea", "ocean", "waters"] },
  "授業": { word: "授業", reading: "じゅぎょう", meanings: ["lesson", "class", "teaching"] },
  "銀行": { word: "銀行", reading: "ぎんこう", meanings: ["bank", "banking institution", "Bank"] },
  "写真": { word: "写真", reading: "しゃしん", meanings: ["photograph", "photo", "picture"] },
  "冬": { word: "冬", reading: "ふゆ", meanings: ["winter", "Winter"] },
  "村": { word: "村", reading: "むら", meanings: ["village", "Village"] },
  "傘": { word: "傘", reading: "かさ", meanings: ["umbrella", "parasol", "something shaped like an umbrella or a conical hat"] },
  "口": { word: "口", reading: "くち", meanings: ["mouth", "opening", "hole"] },
  "橋": { word: "橋", reading: "はし", meanings: ["bridge", "Bridge"] },
  "病院": { word: "病院", reading: "びょういん", meanings: ["hospital", "clinic", "doctor's office"] },
  "図書館": { word: "図書館", reading: "としょかん", meanings: ["library", "Library"] },
  "春": { word: "春", reading: "はる", meanings: ["spring", "springtime", "New Year"] },
  "買い物": { word: "買い物", reading: "かいもの", meanings: ["shopping", "purchased goods", "Shopping"] },
  "椅子": { word: "椅子", reading: "いす", meanings: ["chair", "seat", "stool"] },
  "自動車": { word: "自動車", reading: "じどうしゃ", meanings: ["car", "automobile", "motorcar"] },
  "色": { word: "色", reading: "いろ", meanings: ["colour", "color", "hue"] },
  "卵": { word: "卵", reading: "たまご", meanings: ["eggs", "egg", "spawn"] },
  "肉": { word: "肉", reading: "にく", meanings: ["flesh", "meat", "flesh (of a fruit)"] },
  "風邪": { word: "風邪", reading: "かぜ", meanings: ["(common) cold", "influenza", "flu"] },
  "掃除": { word: "掃除", reading: "そうじ", meanings: ["cleaning", "sweeping", "dusting"] },
  "紙": { word: "紙", reading: "かみ", meanings: ["paper", "Paper"] },
  "鍵": { word: "鍵", reading: "かぎ", meanings: ["key", "lock", "key (to a problem, success, etc.)"] },
  "雑誌": { word: "雑誌", reading: "ざっし", meanings: ["magazine", "journal", "periodical"] },
  "切符": { word: "切符", reading: "きっぷ", meanings: ["ticket", "Ticket"] },
  "外国人": { word: "外国人", reading: "がいこくじん", meanings: ["foreigner", "foreign citizen", "foreign national"] },
  "財布": { word: "財布", reading: "さいふ", meanings: ["wallet", "purse", "coin purse"] },
  "鉛筆": { word: "鉛筆", reading: "えんぴつ", meanings: ["(wooden) pencil", "Pencil"] },
  "大人": { word: "大人", reading: "おとな", meanings: ["adult", "grown-up", "Adult"] },
  "地図": { word: "地図", reading: "ちず", meanings: ["map", "atlas", "chart"] },
  "塩": { word: "塩", reading: "しお", meanings: ["salt", "common salt", "table salt"] },
  "夏休み": { word: "夏休み", reading: "なつやすみ", meanings: ["summer vacation", "summer holiday", "Summer vacation"] },
  "砂糖": { word: "砂糖", reading: "さとう", meanings: ["sugar", "Sugar"] },
  "郵便局": { word: "郵便局", reading: "ゆうびんきょく", meanings: ["post office", "Post office"] },
  "池": { word: "池", reading: "いけ", meanings: ["pond", "Pond"] },
  "教室": { word: "教室", reading: "きょうしつ", meanings: ["classroom", "lecture room", "department (in a university)"] },
  "耳": { word: "耳", reading: "みみ", meanings: ["ear", "hearing", "ear (for music, etc.)"] },
  "切手": { word: "切手", reading: "きって", meanings: ["stamp (postage)", "merchandise certificate", "Postage stamp"] },
  "台所": { word: "台所", reading: "だいどころ", meanings: ["kitchen", "financial situation", "finances"] },
  "電気": { word: "電気", reading: "でんき", meanings: ["electricity", "(electric) light", "Electricity"] },
  "歯": { word: "歯", reading: "は", meanings: ["tooth", "teeth", "tooth (of a comb, saw, etc.)"] },
  "作文": { word: "作文", reading: "さくぶん", meanings: ["writing (an essay, prose, etc.)", "composition", "formal writing with little real meaning"] },
  "紅茶": { word: "紅茶", reading: "こうちゃ", meanings: ["black tea", "Black tea"] },
  "家庭": { word: "家庭", reading: "かてい", meanings: ["home", "household", "family"] },
  "野菜": { word: "野菜", reading: "やさい", meanings: ["vegetable", "marijuana", "cannabis"] },
  "風呂": { word: "風呂", reading: "ふろ", meanings: ["bath", "bathing", "bathtub"] },
  "玄関": { word: "玄関", reading: "げんかん", meanings: ["entrance", "front door", "entryway"] },
  "地下鉄": { word: "地下鉄", reading: "ちかてつ", meanings: ["subway", "metro", "underground (railway)"] },
  "鼻": { word: "鼻", reading: "はな", meanings: ["nose", "Nose"] },
  "緑": { word: "緑", reading: "みどり", meanings: ["green", "greenery", "verdure"] },
  "昼": { word: "昼", reading: "ひる", meanings: ["noon", "midday", "daytime"] },
  "西": { word: "西", reading: "にし", meanings: ["west", "West"] },
  "白": { word: "白", reading: "しろ", meanings: ["white", "innocence", "innocent person"] },
  "洗濯": { word: "洗濯", reading: "せんたく", meanings: ["washing", "laundry", "relaxation"] },
  "冷蔵庫": { word: "冷蔵庫", reading: "れいぞうこ", meanings: ["refrigerator", "fridge", "Refrigerator"] },
  "火曜日": { word: "火曜日", reading: "かようび", meanings: ["Tuesday", "Tuesday"] },
  "南": { word: "南", reading: "みなみ", meanings: ["south", "South"] },
  "北": { word: "北", reading: "きた", meanings: ["north", "the North", "northern territories"] },
  "茶色": { word: "茶色", reading: "ちゃいろ", meanings: ["brown", "light brown", "tawny"] },
  "喫茶店": { word: "喫茶店", reading: "きっさてん", meanings: ["coffee shop", "tearoom", "coffee lounge"] },
  "青": { word: "青", reading: "あお", meanings: ["blue", "azure", "green"] },
  "靴下": { word: "靴下", reading: "くつした", meanings: ["socks", "sock", "stockings"] },
  "封筒": { word: "封筒", reading: "ふうとう", meanings: ["envelope", "Envelope"] },
  "辺": { word: "辺", reading: "へん", meanings: ["area", "vicinity", "region"] },
  "黄色": { word: "黄色", reading: "きいろ", meanings: ["yellow", "amber", "Yellow"] },
  "映画館": { word: "映画館", reading: "えいがかん", meanings: ["movie theatre", "movie theater", "cinema"] },
  "箸": { word: "箸", reading: "はし", meanings: ["chopsticks", "Chopsticks"] },
  "食堂": { word: "食堂", reading: "しょくどう", meanings: ["dining room", "dining hall", "cafeteria"] },
  "牛肉": { word: "牛肉", reading: "ぎゅうにく", meanings: ["beef", "Beef"] },
  "交差点": { word: "交差点", reading: "こうさてん", meanings: ["crossing", "intersection", "Intersection (road)"] },
  "曇り": { word: "曇り", reading: "くもり", meanings: ["cloudiness", "cloudy weather", "fog (on a mirror, glasses, etc.)"] },
  "茶碗": { word: "茶碗", reading: "ちゃわん", meanings: ["rice bowl", "tea cup", "teacup"] },
  "漢字": { word: "漢字", reading: "かんじ", meanings: ["kanji", "Chinese character", "Chinese characters"] },
  "背広": { word: "背広", reading: "せびろ", meanings: ["business suit", "Suit (clothing)"] },
  "万年筆": { word: "万年筆", reading: "まんねんひつ", meanings: ["fountain pen", "Fountain pen"] },
  "灰皿": { word: "灰皿", reading: "はいざら", meanings: ["ashtray", "Ashtray"] },
  "大使館": { word: "大使館", reading: "たいしかん", meanings: ["embassy", "Diplomatic mission"] },
  "豚肉": { word: "豚肉", reading: "ぶたにく", meanings: ["pork", "Pork"] },
  "交番": { word: "交番", reading: "こうばん", meanings: ["police box", "koban", "small neighborhood police station"] },
  "飲む": { word: "飲む", reading: "のむ", meanings: ["to drink", "to swallow", "to take (medicine)"] },
  "上げる": { word: "上げる", reading: "あげる", meanings: ["to raise", "to elevate", "to move something (to a higher place)"] },
  "頭": { word: "頭", reading: "あたま", meanings: ["head", "hair (on one's head)", "mind"] },
  "日曜日": { word: "日曜日", reading: "にちようび", meanings: ["Sunday", "Sunday"] },
  "誕生日": { word: "誕生日", reading: "たんじょうび", meanings: ["birthday", "Birthday"] },
  "可愛い": { word: "可愛い", reading: "かわいい", meanings: ["cute", "adorable", "charming"] },
  "鞄": { word: "鞄", reading: "かばん", meanings: ["bag", "satchel", "briefcase"] },
  "土曜日": { word: "土曜日", reading: "どようび", meanings: ["Saturday", "Saturday"] },
  "月曜日": { word: "月曜日", reading: "げつようび", meanings: ["Monday", "Monday"] },
  "金曜日": { word: "金曜日", reading: "きんようび", meanings: ["Friday", "Friday"] },
  "花瓶": { word: "花瓶", reading: "かびん", meanings: ["(flower) vase", "Vase"] },
  "本棚": { word: "本棚", reading: "ほんだな", meanings: ["bookshelves", "bookshelf", "bookcase"] },
  "木曜日": { word: "木曜日", reading: "もくようび", meanings: ["Thursday", "Thursday"] },
  "石鹸": { word: "石鹸", reading: "せっけん", meanings: ["soap", "Soap"] },
  "水曜日": { word: "水曜日", reading: "すいようび", meanings: ["Wednesday", "Wednesday"] },
  "飴": { word: "飴", reading: "あめ", meanings: ["(hard) candy", "toffee", "rice-sugar"] },
  "八百屋": { word: "八百屋", reading: "やおや", meanings: ["greengrocer", "fruit and vegetable shop", "jack of all trades"] },
  "腕": { word: "腕", reading: "うで", meanings: ["arm", "ability", "skill"] },
  "人形": { word: "人形", reading: "にんぎょう", meanings: ["doll", "puppet", "marionette"] },
  "文化": { word: "文化", reading: "ぶんか", meanings: ["culture", "civilization", "civilisation"] },
  "海岸": { word: "海岸", reading: "かいがん", meanings: ["seashore", "coast", "seaside"] },
  "産業": { word: "産業", reading: "さんぎょう", meanings: ["industry", "livelihood", "occupation"] },
  "動物園": { word: "動物園", reading: "どうぶつえん", meanings: ["zoo", "zoological gardens", "Doubutsuen"] },
  "美術館": { word: "美術館", reading: "びじゅつかん", meanings: ["art museum", "art gallery", "Bijutsukan"] },
  "水道": { word: "水道", reading: "すいどう", meanings: ["water supply", "water service", "waterworks"] },
  "飛行場": { word: "飛行場", reading: "ひこうじょう", meanings: ["airfield", "airport", "aerodrome"] },
  "葡萄": { word: "葡萄", reading: "ぶどう", meanings: ["grape", "grapevine", "Budou"] },
  "成る": { word: "成る", reading: "なる", meanings: ["to become", "to get", "to grow"] },
  "程": { word: "程", reading: "ほど", meanings: ["extent", "degree", "measure"] },
  "事故": { word: "事故", reading: "じこ", meanings: ["accident", "incident", "trouble"] },
  "息子": { word: "息子", reading: "むすこ", meanings: ["son", "penis", "Son"] },
  "生活": { word: "生活", reading: "せいかつ", meanings: ["life", "living", "livelihood"] },
  "注意": { word: "注意", reading: "ちゅうい", meanings: ["attention", "notice", "heed"] },
  "生きる": { word: "生きる", reading: "いきる", meanings: ["to live", "to exist", "to make a living"] },
  "女性": { word: "女性", reading: "じょせい", meanings: ["woman", "female", "feminine gender"] },
  "船": { word: "船", reading: "ふね", meanings: ["ship", "boat", "watercraft"] },
  "説明": { word: "説明", reading: "せつめい", meanings: ["explanation", "exposition", "description"] },
  "警察": { word: "警察", reading: "けいさつ", meanings: ["police", "police officer", "police station"] },
  "危険": { word: "危険", reading: "きけん", meanings: ["danger", "peril", "hazard"] },
  "世界": { word: "世界", reading: "せかい", meanings: ["the world", "society", "the universe"] },
  "戦争": { word: "戦争", reading: "せんそう", meanings: ["war", "fighting", "fierce competition"] },
  "小説": { word: "小説", reading: "しょうせつ", meanings: ["novel", "story", "(work of) fiction"] },
  "関係": { word: "関係", reading: "かんけい", meanings: ["relation", "relationship", "connection"] },
  "研究": { word: "研究", reading: "けんきゅう", meanings: ["research", "study", "investigation"] },
  "会議": { word: "会議", reading: "かいぎ", meanings: ["meeting", "conference", "session"] },
  "音": { word: "音", reading: "おと", meanings: ["sound", "noise", "(musical) note"] },
  "普通": { word: "普通", reading: "ふつう", meanings: ["normal", "ordinary", "regular"] },
  "湖": { word: "湖", reading: "みずうみ", meanings: ["lake", "Lake"] },
  "夢": { word: "夢", reading: "ゆめ", meanings: ["dream", "dream", "hope"] },
  "空港": { word: "空港", reading: "くうこう", meanings: ["airport", "Airport"] },
  "数学": { word: "数学", reading: "すうがく", meanings: ["mathematics", "Mathematics"] },
  "教育": { word: "教育", reading: "きょういく", meanings: ["education", "schooling", "training"] },
  "赤ちゃん": { word: "赤ちゃん", reading: "あかちゃん", meanings: ["baby", "infant", "Infant"] },
  "火": { word: "火", reading: "ひ", meanings: ["fire", "flame", "blaze"] },
  "自由": { word: "自由", reading: "じゆう", meanings: ["freedom", "liberty", "Liberty"] },
  "森": { word: "森", reading: "もり", meanings: ["forest", "shrine grove", "Mori"] },
  "法律": { word: "法律", reading: "ほうりつ", meanings: ["law", "legislation", "act"] },
  "気分": { word: "気分", reading: "きぶん", meanings: ["feeling", "mood", "Mood (psychology)"] },
  "壁": { word: "壁", reading: "かべ", meanings: ["wall", "partition", "barrier"] },
  "田舎": { word: "田舎", reading: "いなか", meanings: ["rural area", "countryside", "the sticks"] },
  "気": { word: "気", reading: "き", meanings: ["spirit", "mind", "heart"] },
  "男性": { word: "男性", reading: "だんせい", meanings: ["man", "male", "masculine gender"] },
  "地震": { word: "地震", reading: "じしん", meanings: ["earthquake", "Earthquake"] },
  "故障": { word: "故障", reading: "こしょう", meanings: ["fault", "trouble", "breakdown"] },
  "人口": { word: "人口", reading: "じんこう", meanings: ["population", "common talk", "Population"] },
  "残念": { word: "残念", reading: "ざんねん", meanings: ["regrettable", "unfortunate", "disappointing"] },
  "島": { word: "島", reading: "しま", meanings: ["island", "one's territory (of a sex worker, organized crime gang, etc.)", "one's turf"] },
  "歴史": { word: "歴史", reading: "れきし", meanings: ["history", "History"] },
  "教会": { word: "教会", reading: "きょうかい", meanings: ["church", "congregation", "Christian Church"] },
  "社会": { word: "社会", reading: "しゃかい", meanings: ["society", "public", "community"] },
  "住所": { word: "住所", reading: "じゅうしょ", meanings: ["address (of a home, business, etc.)", "residence", "domicile"] },
  "工場": { word: "工場", reading: "こうじょう", meanings: ["factory", "plant", "mill"] },
  "趣味": { word: "趣味", reading: "しゅみ", meanings: ["hobby", "pastime", "tastes"] },
  "経済": { word: "経済", reading: "けいざい", meanings: ["economy", "economics", "finance"] },
  "台風": { word: "台風", reading: "たいふう", meanings: ["typhoon", "hurricane", "Typhoon"] },
  "卒業": { word: "卒業", reading: "そつぎょう", meanings: ["graduation", "completion (of a course)", "moving on (from)"] },
  "雲": { word: "雲", reading: "くも", meanings: ["cloud", "Cloud"] },
  "光": { word: "光", reading: "ひかり", meanings: ["light", "illumination", "ray"] },
  "贈り物": { word: "贈り物", reading: "おくりもの", meanings: ["present", "gift", "Gift"] },
  "科学": { word: "科学", reading: "かがく", meanings: ["science", "to think about scientifically", "to think in terms of science"] },
  "政治": { word: "政治", reading: "せいじ", meanings: ["politics", "government", "Politics"] },
  "特別": { word: "特別", reading: "とくべつ", meanings: ["special", "particular", "extraordinary"] },
  "水泳": { word: "水泳", reading: "すいえい", meanings: ["swimming", "Human swimming"] },
  "講義": { word: "講義", reading: "こうぎ", meanings: ["lecture", "Lecture"] },
  "指": { word: "指", reading: "ゆび", meanings: ["finger", "toe", "digit"] },
  "生産": { word: "生産", reading: "せいさん", meanings: ["production", "manufacture", "Outline of industrial organization"] },
  "会話": { word: "会話", reading: "かいわ", meanings: ["conversation", "talk", "chat"] },
  "季節": { word: "季節", reading: "きせつ", meanings: ["season", "time of year", "Season"] },
  "玩具": { word: "玩具", reading: "おもちゃ", meanings: ["toy", "(person or thing treated as a) plaything", "Toy"] },
  "翻訳": { word: "翻訳", reading: "ほんやく", meanings: ["translation", "deciphering", "decoding"] },
  "貿易": { word: "貿易", reading: "ぼうえき", meanings: ["(foreign) trade", "(international) commerce", "importing and exporting"] },
  "文学": { word: "文学", reading: "ぶんがく", meanings: ["literature", "Literature"] },
  "葉": { word: "葉", reading: "は", meanings: ["leaf", "blade (of grass)", "(pine) needle"] },
  "交通": { word: "交通", reading: "こうつう", meanings: ["traffic", "transportation", "communication"] },
  "遊び": { word: "遊び", reading: "あそび", meanings: ["play", "playing", "game"] },
  "道具": { word: "道具", reading: "どうぐ", meanings: ["tool", "implement", "instrument"] },
  "入学": { word: "入学", reading: "にゅうがく", meanings: ["admission (to a school or university)", "entrance", "enrolment"] },
  "背中": { word: "背中", reading: "せなか", meanings: ["back (of the body)", "Human back"] },
  "指輪": { word: "指輪", reading: "ゆびわ", meanings: ["(finger) ring", "Ring (jewellery)"] },
  "発音": { word: "発音", reading: "はつおん", meanings: ["pronunciation", "production of sound", "Pronunciation"] },
  "医学": { word: "医学", reading: "いがく", meanings: ["medicine", "medical science", "Medicine"] },
  "漫画": { word: "漫画", reading: "まんが", meanings: ["cartoon", "comic", "comic strip"] },
  "鏡": { word: "鏡", reading: "かがみ", meanings: ["mirror", "looking-glass", "barrel head"] },
  "電報": { word: "電報", reading: "でんぽう", meanings: ["telegram", "Telegraphy"] },
  "校長": { word: "校長", reading: "こうちょう", meanings: ["principal", "head teacher", "headmaster"] },
  "市民": { word: "市民", reading: "しみん", meanings: ["citizen (of a country)", "citizenry", "citizen (of a city)"] },
  "郊外": { word: "郊外", reading: "こうがい", meanings: ["suburb", "residential area on the outskirt of a city", "commuter belt"] },
  "国際": { word: "国際", reading: "こくさい", meanings: ["international", "diplomatic intercourse", "International"] },
  "砂": { word: "砂", reading: "すな", meanings: ["sand", "grit", "fine gravel"] },
  "手袋": { word: "手袋", reading: "てぶくろ", meanings: ["glove", "mitten", "mitt"] },
  "日記": { word: "日記", reading: "にっき", meanings: ["diary", "journal", "Diary"] },
  "絹": { word: "絹", reading: "きぬ", meanings: ["silk", "Silk"] },
  "糸": { word: "糸", reading: "いと", meanings: ["thread", "yarn", "string"] },
  "文法": { word: "文法", reading: "ぶんぽう", meanings: ["grammar", "Grammar"] },
  "神社": { word: "神社", reading: "じんじゃ", meanings: ["Shinto shrine", "Shinto shrine"] },
  "展覧会": { word: "展覧会", reading: "てんらんかい", meanings: ["exhibition", "Art exhibition"] },
  "小学校": { word: "小学校", reading: "しょうがっこう", meanings: ["primary school", "elementary school", "grade school"] },
  "駐車場": { word: "駐車場", reading: "ちゅうしゃじょう", meanings: ["parking lot", "car park", "carpark"] },
  "先輩": { word: "先輩", reading: "せんぱい", meanings: ["senior (at school, work, etc.)", "superior", "elder"] },
  "西洋": { word: "西洋", reading: "せいよう", meanings: ["the West", "the Occident", "Western countries"] },
  "注射": { word: "注射", reading: "ちゅうしゃ", meanings: ["injection", "jab", "shot"] },
  "坂": { word: "坂", reading: "さか", meanings: ["slope", "incline", "hill"] },
  "乗り物": { word: "乗り物", reading: "のりもの", meanings: ["vehicle", "conveyance", "(means of) transport"] },
  "旅館": { word: "旅館", reading: "りょかん", meanings: ["ryokan", "traditional Japanese inn", "Ryokan (Japanese inn)"] },
  "林": { word: "林", reading: "はやし", meanings: ["wood", "woods", "forest"] },
  "布団": { word: "布団", reading: "ふとん", meanings: ["futon", "Japanese bedding consisting of a mattress and a duvet", "round cushion used for Zen meditation (traditionally made of woven bulrush leaves)"] },
  "中学校": { word: "中学校", reading: "ちゅうがっこう", meanings: ["junior high school", "middle school", "lower secondary school"] },
  "研究室": { word: "研究室", reading: "けんきゅうしつ", meanings: ["laboratory", "seminar room", "professor's office"] },
  "会議室": { word: "会議室", reading: "かいぎしつ", meanings: ["conference room", "council room", "Conference hall"] },
  "柔道": { word: "柔道", reading: "じゅうどう", meanings: ["judo", "Judo"] },
  "花見": { word: "花見", reading: "はなみ", meanings: ["cherry blossom viewing", "flower viewing", "Hanami"] },
  "公務員": { word: "公務員", reading: "こうむいん", meanings: ["public employee", "government employee", "public-sector worker"] },
  "高等学校": { word: "高等学校", reading: "こうとうがっこう", meanings: ["senior high school", "high school", "High school"] },
  "辞典": { word: "辞典", reading: "じてん", meanings: ["dictionary", "lexicon", "Dictionary"] },
  "心": { word: "心", reading: "こころ", meanings: ["mind", "heart", "spirit"] },
  "力": { word: "力", reading: "ちから", meanings: ["force", "strength", "might"] },
  "喧嘩": { word: "喧嘩", reading: "けんか", meanings: ["quarrel", "brawl", "fight"] },
  "天気予報": { word: "天気予報", reading: "てんきよほう", meanings: ["weather forecast", "weather report", "Weather forecasting"] },
  "髭": { word: "髭", reading: "ひげ", meanings: ["moustache", "mustache", "beard"] },
  "押入れ": { word: "押入れ", reading: "おしいれ", meanings: ["closet (built into the wall, usu. with sliding doors)", "(built-in) wardrobe", "Closet"] },
  "味噌": { word: "味噌", reading: "みそ", meanings: ["miso", "fermented condiment usu. made from soybeans", "innards (from crabs, shrimps, etc.) resembling miso"] },
  "正直": { word: "正直", reading: "しょうじき", meanings: ["honest", "frank", "candid"] },
  "一致": { word: "一致", reading: "いっち", meanings: ["agreement", "accord", "correspondence"] },
  "博物館": { word: "博物館", reading: "はくぶつかん", meanings: ["museum", "Hakubutsukan", "Museum"] },
  "皿": { word: "皿", reading: "さら", meanings: ["plate", "dish", "platter"] },
  "舞台": { word: "舞台", reading: "ぶたい", meanings: ["stage (of a theatre, concert hall, etc.)", "stage performance", "stage production"] },
  "寄付": { word: "寄付", reading: "きふ", meanings: ["contribution", "donation", "Kifu"] },
  "猿": { word: "猿", reading: "さる", meanings: ["monkey (esp. the Japanese macaque, Macaca fuscata)", "ape", "non-human primate"] },
  "平等": { word: "平等", reading: "びょうどう", meanings: ["equality", "impartiality", "evenness"] },
  "金属": { word: "金属", reading: "きんぞく", meanings: ["metal", "Kinzoku", "Metal"] },
  "左右": { word: "左右", reading: "さゆう", meanings: ["left and right", "right and left", "(asserting) control"] },
  "商人": { word: "商人", reading: "しょうにん", meanings: ["merchant", "trader", "tradesman"] },
  "国境": { word: "国境", reading: "こっきょう", meanings: ["border (between countries)", "national border", "Kunizakai"] },
  "集団": { word: "集団", reading: "しゅうだん", meanings: ["group", "mass", "Shuudan"] },
  "根": { word: "根", reading: "ね", meanings: ["root (of a plant)", "root (of a tooth, hair, etc.)", "center (of a pimple, etc.)"] },
  "鎖": { word: "鎖", reading: "くさり", meanings: ["chain", "chains", "Kusari"] },
  "より": { word: "より", reading: "より", meanings: ["than", "rather than", "instead of"] },
  "一番": { word: "一番", reading: "いちばん", meanings: ["number one", "first", "first place"] },
  "私": { word: "私", reading: "わたし", meanings: ["I", "me"] },
  "外": { word: "外", reading: "そと", meanings: ["outside", "exterior", "the open (air)"] },
  "姉": { word: "姉", reading: "あね", meanings: ["older sister", "elder sister", "Ane"] },
  "百": { word: "百", reading: "ひゃく", meanings: ["hundred", "100", "Hyaku"] },
  "時": { word: "時", reading: "とき", meanings: ["time", "hour", "moment"] },
  "元": { word: "元", reading: "もと", meanings: ["origin", "source", "beginning"] },
  "計画": { word: "計画", reading: "けいかく", meanings: ["plan", "project", "schedule"] },
  "少年": { word: "少年", reading: "しょうねん", meanings: ["boy", "juvenile", "child"] },
  "列車": { word: "列車", reading: "れっしゃ", meanings: ["train", "railway train", "Train"] },
  "健康": { word: "健康", reading: "けんこう", meanings: ["health", "healthy", "sound"] },
  "人間": { word: "人間", reading: "にんげん", meanings: ["human being", "human", "person"] },
  "結果": { word: "結果", reading: "けっか", meanings: ["result", "consequence", "outcome"] },
  "理解": { word: "理解", reading: "りかい", meanings: ["understanding", "comprehension", "appreciation"] },
  "少女": { word: "少女", reading: "しょうじょ", meanings: ["girl (usu. between 7 and 17)", "young lady", "female between 17 and 20 years old (ritsuryō period)"] },
  "事実": { word: "事実", reading: "じじつ", meanings: ["fact", "truth", "reality"] },
  "食事": { word: "食事", reading: "しょくじ", meanings: ["meal (e.g. lunch, dinner)", "diet", "Meal"] },
  "人生": { word: "人生", reading: "じんせい", meanings: ["(one's) life", "Human life"] },
  "母親": { word: "母親", reading: "ははおや", meanings: ["mother", "Mother"] },
  "行動": { word: "行動", reading: "こうどう", meanings: ["action", "conduct", "behaviour"] },
  "父親": { word: "父親", reading: "ちちおや", meanings: ["father", "Father"] },
  "太陽": { word: "太陽", reading: "たいよう", meanings: ["Sun", "Sun"] },
  "幸福": { word: "幸福", reading: "こうふく", meanings: ["happiness", "well-being", "joy"] },
  "政府": { word: "政府", reading: "せいふ", meanings: ["government", "administration", "ministry"] },
  "経験": { word: "経験", reading: "けいけん", meanings: ["experience", "Experience"] },
  "責任": { word: "責任", reading: "せきにん", meanings: ["duty", "responsibility (incl. supervision of staff)", "liability"] },
  "我慢": { word: "我慢", reading: "がまん", meanings: ["endurance", "patience", "perseverance"] },
  "噂": { word: "噂", reading: "うわさ", meanings: ["rumour", "rumor", "report"] },
  "道路": { word: "道路", reading: "どうろ", meanings: ["road", "highway", "Road"] },
  "機械": { word: "機械", reading: "きかい", meanings: ["machine", "mechanism", "instrument"] },
  "地球": { word: "地球", reading: "ちきゅう", meanings: ["Earth", "the globe", "Earth"] },
  "秘密": { word: "秘密", reading: "ひみつ", meanings: ["secret", "secrecy", "confidentiality"] },
  "偶然": { word: "偶然", reading: "ぐうぜん", meanings: ["coincidence", "chance", "accident"] },
  "情報": { word: "情報", reading: "じょうほう", meanings: ["information", "news", "report"] },
  "現在": { word: "現在", reading: "げんざい", meanings: ["the present", "present time", "now"] },
  "昼食": { word: "昼食", reading: "ちゅうしょく", meanings: ["lunch", "midday meal", "Lunch"] },
  "期待": { word: "期待", reading: "きたい", meanings: ["expectation", "anticipation", "hope"] },
  "嵐": { word: "嵐", reading: "あらし", meanings: ["storm", "tempest", "uproar"] },
  "丘": { word: "丘", reading: "おか", meanings: ["hill", "height", "knoll"] },
  "運動": { word: "運動", reading: "うんどう", meanings: ["exercise", "physical training", "workout"] },
  "大統領": { word: "大統領", reading: "だいとうりょう", meanings: ["president (of a country)", "big man", "boss"] },
  "演説": { word: "演説", reading: "えんぜつ", meanings: ["speech", "address", "Public speaking"] },
  "神": { word: "神", reading: "かみ", meanings: ["god", "deity", "divinity"] },
  "馬": { word: "馬", reading: "うま", meanings: ["horse", "horse racing", "promoted bishop"] },
  "読書": { word: "読書", reading: "どくしょ", meanings: ["reading (books)", "Reading (process)"] },
  "詩": { word: "詩", reading: "し", meanings: ["poem", "poetry", "verse"] },
  "知識": { word: "知識", reading: "ちしき", meanings: ["knowledge", "information", "Knowledge"] },
  "都市": { word: "都市", reading: "とし", meanings: ["town", "city", "municipal"] },
  "収入": { word: "収入", reading: "しゅうにゅう", meanings: ["income", "earnings", "revenue"] },
  "嘘": { word: "嘘", reading: "うそ", meanings: ["lie", "fib", "falsehood"] },
  "詩人": { word: "詩人", reading: "しじん", meanings: ["poet", "Poet"] },
  "涙": { word: "涙", reading: "なみだ", meanings: ["tear", "tears", "lachrymal secretion"] },
  "円": { word: "円", reading: "えん", meanings: ["yen (currency of Japan)", "circle", "圓"] },
  "酒": { word: "酒", reading: "さけ", meanings: ["alcohol", "sake", "Alcoholic beverage"] },
  "財産": { word: "財産", reading: "ざいさん", meanings: ["property", "fortune", "assets"] },
  "発見": { word: "発見", reading: "はっけん", meanings: ["discovery", "detection", "finding"] },
  "勇気": { word: "勇気", reading: "ゆうき", meanings: ["courage", "bravery", "valour"] },
  "解決": { word: "解決", reading: "かいけつ", meanings: ["settlement", "solution", "resolution"] },
  "学者": { word: "学者", reading: "がくしゃ", meanings: ["scholar", "academic", "scientist"] },
  "患者": { word: "患者", reading: "かんじゃ", meanings: ["patient", "Patient"] },
  "存在": { word: "存在", reading: "そんざい", meanings: ["existence", "being", "presence"] },
  "言語": { word: "言語", reading: "げんご", meanings: ["language", "Language"] },
  "信頼": { word: "信頼", reading: "しんらい", meanings: ["trust (in)", "confidence", "faith"] },
  "海外": { word: "海外", reading: "かいがい", meanings: ["foreign", "abroad", "overseas"] },
  "作家": { word: "作家", reading: "さっか", meanings: ["author", "writer", "novelist"] },
  "平和": { word: "平和", reading: "へいわ", meanings: ["peace", "harmony", "Peace"] },
  "希望": { word: "希望", reading: "きぼう", meanings: ["hope", "wish", "aspiration"] },
  "調査": { word: "調査", reading: "ちょうさ", meanings: ["investigation", "examination", "inquiry"] },
  "地域": { word: "地域", reading: "ちいき", meanings: ["area", "region", "district"] },
  "気候": { word: "気候", reading: "きこう", meanings: ["climate", "Climate"] },
  "実験": { word: "実験", reading: "じっけん", meanings: ["experiment", "experimentation", "Experiment"] },
  "愛": { word: "愛", reading: "あい", meanings: ["love", "affection", "care"] },
  "国民": { word: "国民", reading: "こくみん", meanings: ["people (of a country)", "nation", "citizen"] },
  "権利": { word: "権利", reading: "けんり", meanings: ["right", "privilege", "Rights"] },
  "騒音": { word: "騒音", reading: "そうおん", meanings: ["noise", "din", "Noise pollution"] },
  "義務": { word: "義務", reading: "ぎむ", meanings: ["duty", "obligation", "responsibility"] },
  "釣り": { word: "釣り", reading: "つり", meanings: ["fishing", "angling", "change (for a purchase)"] },
  "胸": { word: "胸", reading: "むね", meanings: ["chest", "breast", "breasts"] },
  "過去": { word: "過去", reading: "かこ", meanings: ["the past", "bygone days", "one's past (that one would prefer remained secret)"] },
  "物価": { word: "物価", reading: "ぶっか", meanings: ["prices of commodities", "prices (in general)", "cost-of-living"] },
  "利益": { word: "利益", reading: "りえき", meanings: ["profit", "gains", "benefit"] },
  "植物": { word: "植物", reading: "しょくぶつ", meanings: ["plant", "vegetation", "Plant"] },
  "発明": { word: "発明", reading: "はつめい", meanings: ["invention", "intelligent", "clever"] },
  "教授": { word: "教授", reading: "きょうじゅ", meanings: ["professor", "teaching", "instruction"] },
  "氷": { word: "氷", reading: "こおり", meanings: ["ice", "shaved ice (usually served with flavored simple syrup)", "Ice"] },
  "痛み": { word: "痛み", reading: "いたみ", meanings: ["pain", "ache", "soreness"] },
  "石油": { word: "石油", reading: "せきゆ", meanings: ["oil", "petroleum", "kerosene"] },
  "進歩": { word: "進歩", reading: "しんぽ", meanings: ["progress", "advance", "improvement"] },
  "物語": { word: "物語", reading: "ものがたり", meanings: ["story", "tale", "narrative"] },
  "感情": { word: "感情", reading: "かんじょう", meanings: ["emotion", "feeling", "feelings"] },
  "週": { word: "週", reading: "しゅう", meanings: ["week", "Week"] },
  "屋根": { word: "屋根", reading: "やね", meanings: ["roof", "Roof"] },
  "議長": { word: "議長", reading: "ぎちょう", meanings: ["chair", "chairman", "chairperson"] },
  "恐怖": { word: "恐怖", reading: "きょうふ", meanings: ["fear", "dread", "dismay"] },
  "商品": { word: "商品", reading: "しょうひん", meanings: ["commodity", "article of commerce", "goods"] },
  "否定": { word: "否定", reading: "ひてい", meanings: ["denial", "negation", "repudiation"] },
  "費用": { word: "費用", reading: "ひよう", meanings: ["cost", "expense", "Cost"] },
  "賞": { word: "賞", reading: "しょう", meanings: ["prize", "award", "Award"] },
  "作品": { word: "作品", reading: "さくひん", meanings: ["work (e.g. book, film, painting, composition)", "piece", "production"] },
  "留学": { word: "留学", reading: "りゅうがく", meanings: ["studying abroad", "(temporarily) studying at another school (to learn a specific skill)", "Study abroad in the United States"] },
  "価格": { word: "価格", reading: "かかく", meanings: ["price", "value", "cost"] },
  "城": { word: "城", reading: "しろ", meanings: ["castle", "Castle"] },
  "犯罪": { word: "犯罪", reading: "はんざい", meanings: ["crime", "offence", "offense"] },
  "肩": { word: "肩", reading: "かた", meanings: ["shoulder", "Shoulder"] },
  "意志": { word: "意志", reading: "いし", meanings: ["will", "volition", "intention"] },
  "正午": { word: "正午", reading: "しょうご", meanings: ["noon", "midday", "Noon"] },
  "評価": { word: "評価", reading: "ひょうか", meanings: ["valuation", "appraisal", "evaluation"] },
  "職業": { word: "職業", reading: "しょくぎょう", meanings: ["occupation", "profession", "job"] },
  "家具": { word: "家具", reading: "かぐ", meanings: ["furniture", "Furniture"] },
  "劇場": { word: "劇場", reading: "げきじょう", meanings: ["theatre", "theater", "playhouse"] },
  "不安": { word: "不安", reading: "ふあん", meanings: ["anxiety", "uneasiness", "worry"] },
  "首相": { word: "首相", reading: "しゅしょう", meanings: ["prime minister", "chancellor (Germany, Austria, etc.)", "premier"] },
  "自然": { word: "自然", reading: "しぜん", meanings: ["nature", "natural", "spontaneous"] },
  "自殺": { word: "自殺", reading: "じさつ", meanings: ["suicide", "Suicide"] },
  "意識": { word: "意識", reading: "いしき", meanings: ["consciousness", "becoming aware (of)", "awareness"] },
  "逮捕": { word: "逮捕", reading: "たいほ", meanings: ["arrest", "apprehension", "capture"] },
  "爆発": { word: "爆発", reading: "ばくはつ", meanings: ["explosion", "detonation", "blast"] },
  "論文": { word: "論文", reading: "ろんぶん", meanings: ["thesis", "essay", "treatise"] },
  "記録": { word: "記録", reading: "きろく", meanings: ["record", "document", "minutes"] },
  "世紀": { word: "世紀", reading: "せいき", meanings: ["century", "era", "of the century (e.g. fight of the century)"] },
  "頭痛": { word: "頭痛", reading: "ずつう", meanings: ["headache", "Headache"] },
  "契約": { word: "契約", reading: "けいやく", meanings: ["contract", "compact", "agreement"] },
  "牛": { word: "牛", reading: "うし", meanings: ["cattle (Bos taurus)", "cow", "bull"] },
  "優勝": { word: "優勝", reading: "ゆうしょう", meanings: ["overall victory", "championship", "winning the title"] },
  "独立": { word: "独立", reading: "どくりつ", meanings: ["independence", "self-reliance", "supporting oneself"] },
  "記憶": { word: "記憶", reading: "きおく", meanings: ["memory", "recollection", "remembrance"] },
  "俳優": { word: "俳優", reading: "はいゆう", meanings: ["actor", "actress", "player"] },
  "額": { word: "額", reading: "がく", meanings: ["(picture) frame", "framed picture", "amount (esp. of money)"] },
  "州": { word: "州", reading: "しゅう", meanings: ["state (of the US, Australia, India, Germany, etc.)", "province (e.g. of Canada)", "county (e.g. of the UK)"] },
  "公平": { word: "公平", reading: "こうへい", meanings: ["fairness", "impartiality", "justice"] },
  "強盗": { word: "強盗", reading: "ごうとう", meanings: ["robber", "mugger", "robbery"] },
  "生命": { word: "生命", reading: "せいめい", meanings: ["life", "existence", "(one's) working life"] },
  "輸入": { word: "輸入", reading: "ゆにゅう", meanings: ["import", "importation", "introduction"] },
  "記事": { word: "記事", reading: "きじ", meanings: ["article", "news story", "report"] },
  "命令": { word: "命令", reading: "めいれい", meanings: ["order", "command", "decree"] },
  "霧": { word: "霧", reading: "きり", meanings: ["fog", "mist", "spray"] },
  "合図": { word: "合図", reading: "あいず", meanings: ["sign", "signal", "cue"] },
  "宇宙": { word: "宇宙", reading: "うちゅう", meanings: ["universe", "cosmos", "space"] },
  "銃": { word: "銃", reading: "じゅう", meanings: ["gun", "firearm", "small arms (e.g. rifle, pistol, etc)"] },
  "計算": { word: "計算", reading: "けいさん", meanings: ["calculation", "computation", "reckoning"] },
  "医師": { word: "医師", reading: "いし", meanings: ["doctor", "physician", "Physician"] },
  "禁煙": { word: "禁煙", reading: "きんえん", meanings: ["abstaining from smoking", "quitting smoking", "prohibition of smoking"] },
  "現実": { word: "現実", reading: "げんじつ", meanings: ["reality", "actuality", "hard fact"] },
  "握手": { word: "握手", reading: "あくしゅ", meanings: ["handshake", "reconciliation", "joining hands"] },
  "友情": { word: "友情", reading: "ゆうじょう", meanings: ["friendship", "fellowship", "camaraderie"] },
  "訓練": { word: "訓練", reading: "くんれん", meanings: ["training", "drill", "practice"] },
  "香り": { word: "香り", reading: "かおり", meanings: ["aroma", "fragrance", "scent"] },
  "生物": { word: "生物", reading: "せいぶつ", meanings: ["living thing", "organism", "creature"] },
  "攻撃": { word: "攻撃", reading: "こうげき", meanings: ["attack", "assault", "raid"] },
  "企業": { word: "企業", reading: "きぎょう", meanings: ["enterprise", "business", "company"] },
  "方向": { word: "方向", reading: "ほうこう", meanings: ["direction", "orientation", "bearing"] },
  "芸術": { word: "芸術", reading: "げいじゅつ", meanings: ["art", "the arts", "Art"] },
  "役割": { word: "役割", reading: "やくわり", meanings: ["part", "assigning (allotment of) parts", "role"] },
  "宗教": { word: "宗教", reading: "しゅうきょう", meanings: ["religion", "religious affiliation", "belief"] },
  "流れ": { word: "流れ", reading: "ながれ", meanings: ["flow (of a fluid or gas)", "stream", "current"] },
  "羽": { word: "羽", reading: "はね", meanings: ["feather", "plume", "down"] },
  "波": { word: "波", reading: "なみ", meanings: ["wave", "billow", "ripple"] },
  "服装": { word: "服装", reading: "ふくそう", meanings: ["attire", "dress", "clothes"] },
  "広告": { word: "広告", reading: "こうこく", meanings: ["advertisement", "advertising", "announcement"] },
  "個人": { word: "個人", reading: "こじん", meanings: ["individual", "private person", "personal"] },
  "署名": { word: "署名", reading: "しょめい", meanings: ["signature", "autograph", "Signature"] },
  "無料": { word: "無料", reading: "むりょう", meanings: ["free (of charge)", "gratuitous", "Gratis"] },
  "駐車": { word: "駐車", reading: "ちゅうしゃ", meanings: ["parking (a vehicle)", "Parking"] },
  "王様": { word: "王様", reading: "おうさま", meanings: ["king", "Ōsama (musician)"] },
  "現金": { word: "現金", reading: "げんきん", meanings: ["cash", "ready money", "money on hand"] },
  "証明": { word: "証明", reading: "しょうめい", meanings: ["proof", "testimony", "demonstration"] },
  "宝石": { word: "宝石", reading: "ほうせき", meanings: ["gem", "jewel", "precious stone"] },
  "博士": { word: "博士", reading: "はかせ", meanings: ["expert", "learned person", "doctor"] },
  "話題": { word: "話題", reading: "わだい", meanings: ["topic", "subject", "much talked about"] },
  "芝居": { word: "芝居", reading: "しばい", meanings: ["play", "drama", "Acting"] },
  "塔": { word: "塔", reading: "とう", meanings: ["tower", "steeple", "spire"] },
  "出版": { word: "出版", reading: "しゅっぱん", meanings: ["publication", "Publishing"] },
  "保証": { word: "保証", reading: "ほしょう", meanings: ["guarantee", "security", "assurance"] },
  "競技": { word: "競技", reading: "きょうぎ", meanings: ["game", "match", "contest"] },
  "軍隊": { word: "軍隊", reading: "ぐんたい", meanings: ["armed forces", "military", "troops"] },
  "投票": { word: "投票", reading: "とうひょう", meanings: ["voting", "ballot", "poll"] },
  "離婚": { word: "離婚", reading: "りこん", meanings: ["divorce", "Divorce"] },
  "診察": { word: "診察", reading: "しんさつ", meanings: ["medical examination", "checkup", "consultation"] },
  "年寄り": { word: "年寄り", reading: "としより", meanings: ["old person", "elderly person", "senior citizen"] },
  "心臓": { word: "心臓", reading: "しんぞう", meanings: ["heart", "guts", "nerve"] },
  "衝突": { word: "衝突", reading: "しょうとつ", meanings: ["collision", "crash", "impact"] },
  "販売": { word: "販売", reading: "はんばい", meanings: ["sale", "sales", "selling"] },
  "型": { word: "型", reading: "かた", meanings: ["type", "style", "model"] },
  "輸出": { word: "輸出", reading: "ゆしゅつ", meanings: ["export", "exportation", "efferent"] },
  "平均": { word: "平均", reading: "へいきん", meanings: ["average", "mean", "balance"] },
  "冒険": { word: "冒険", reading: "ぼうけん", meanings: ["adventure", "venture", "venture which is unlikely to succeed"] },
  "永遠": { word: "永遠", reading: "えいえん", meanings: ["eternity", "perpetuity", "permanence"] },
  "未来": { word: "未来", reading: "みらい", meanings: ["(distant) future", "future existence", "world beyond the grave"] },
  "表情": { word: "表情", reading: "ひょうじょう", meanings: ["facial expression", "countenance", "look"] },
  "女王": { word: "女王", reading: "じょおう", meanings: ["queen", "female champion", "Queen regnant"] },
  "小屋": { word: "小屋", reading: "こや", meanings: ["hut", "cabin", "shed"] },
  "胃": { word: "胃", reading: "い", meanings: ["stomach", "Chinese \"stomach\" constellation (one of the 28 mansions)", "Stomach"] },
  "通学": { word: "通学", reading: "つうがく", meanings: ["commuting to school", "school commute", "Student transport"] },
  "改善": { word: "改善", reading: "かいぜん", meanings: ["betterment", "improvement", "kaizen (Japanese business philosophy of continuous improvement)"] },
  "畑": { word: "畑", reading: "はたけ", meanings: ["field (for growing wheat, fruit, vegetables, etc.)", "cultivated land", "vegetable plot"] },
  "制度": { word: "制度", reading: "せいど", meanings: ["system", "institution", "organization"] },
  "青年": { word: "青年", reading: "せいねん", meanings: ["youth", "young man", "Youth"] },
  "虎": { word: "虎", reading: "とら", meanings: ["tiger (Panthera tigris)", "drunkard", "drunk"] },
  "雷": { word: "雷", reading: "かみなり", meanings: ["lightning", "thunder", "thunderbolt"] },
  "放送": { word: "放送", reading: "ほうそう", meanings: ["broadcasting", "broadcast", "program"] },
  "観客": { word: "観客", reading: "かんきゃく", meanings: ["spectator", "audience", "Audience"] },
  "中心": { word: "中心", reading: "ちゅうしん", meanings: ["center", "centre", "middle"] },
  "収穫": { word: "収穫", reading: "しゅうかく", meanings: ["harvest", "crop", "ingathering"] },
  "籠": { word: "籠", reading: "かご", meanings: ["basket (shopping, etc.)", "hamper", "cage"] },
  "信号": { word: "信号", reading: "しんごう", meanings: ["signal", "signalling", "signaling"] },
  "袋": { word: "袋", reading: "ふくろ", meanings: ["bag", "sack", "pouch"] },
  "国家": { word: "国家", reading: "こっか", meanings: ["state", "country", "nation"] },
  "節約": { word: "節約", reading: "せつやく", meanings: ["economising", "saving", "Saving"] },
  "化学": { word: "化学", reading: "かがく", meanings: ["chemistry", "Chemistry"] },
  "建設": { word: "建設", reading: "けんせつ", meanings: ["construction", "establishment", "Construction"] },
  "睡眠": { word: "睡眠", reading: "すいみん", meanings: ["sleep", "Sleep"] },
  "教科書": { word: "教科書", reading: "きょうかしょ", meanings: ["textbook", "coursebook", "schoolbook"] },
  "油": { word: "油", reading: "あぶら", meanings: ["oil", "Oil"] },
  "毒": { word: "毒", reading: "どく", meanings: ["poison", "toxicant", "venom"] },
  "座席": { word: "座席", reading: "ざせき", meanings: ["seat (esp. in public places or places with assigned seating)", "seating", "Seat"] },
  "単位": { word: "単位", reading: "たんい", meanings: ["unit (e.g. meters, grams, etc.)", "denomination", "unit (i.e. one comprised of many)"] },
  "郵便": { word: "郵便", reading: "ゆうびん", meanings: ["mail service", "postal service", "mail"] },
  "常識": { word: "常識", reading: "じょうしき", meanings: ["common sense", "good sense", "common knowledge"] },
  "誕生": { word: "誕生", reading: "たんじょう", meanings: ["birth (of a person)", "nativity", "creation"] },
  "労働": { word: "労働", reading: "ろうどう", meanings: ["labor", "labour", "work"] },
  "運": { word: "運", reading: "うん", meanings: ["fortune", "luck", "chance"] },
  "家事": { word: "家事", reading: "かじ", meanings: ["housework", "domestic chores", "family affairs"] },
  "数字": { word: "数字", reading: "すうじ", meanings: ["numeral", "digit", "numeric character"] },
  "食欲": { word: "食欲", reading: "しょくよく", meanings: ["appetite (for food)", "Appetite"] },
  "学習": { word: "学習", reading: "がくしゅう", meanings: ["learning", "study", "Learning"] },
  "失業": { word: "失業", reading: "しつぎょう", meanings: ["unemployment", "losing one's job", "becoming unemployed"] },
  "観光": { word: "観光", reading: "かんこう", meanings: ["sightseeing", "tourism", "Tourism"] },
  "汗": { word: "汗", reading: "あせ", meanings: ["sweat", "perspiration", "moisture"] },
  "毛布": { word: "毛布", reading: "もうふ", meanings: ["blanket", "Blanket"] },
  "婚約": { word: "婚約", reading: "こんやく", meanings: ["engagement", "betrothal", "Engagement"] },
  "分析": { word: "分析", reading: "ぶんせき", meanings: ["analysis", "Analysis"] },
  "知恵": { word: "知恵", reading: "ちえ", meanings: ["wisdom", "wit", "sagacity"] },
  "首都": { word: "首都", reading: "しゅと", meanings: ["(national) capital (city)", "metropolis", "Capital city"] },
  "書斎": { word: "書斎", reading: "しょさい", meanings: ["study", "library", "den"] },
  "引用": { word: "引用", reading: "いんよう", meanings: ["quotation", "citation", "reference"] },
  "武器": { word: "武器", reading: "ぶき", meanings: ["weapon", "arms", "ordnance"] },
  "砂漠": { word: "砂漠", reading: "さばく", meanings: ["desert", "Desert"] },
  "鉄": { word: "鉄", reading: "てつ", meanings: ["iron (Fe)", "steel", "iron (will, discipline, lady, etc.)"] },
  "異常": { word: "異常", reading: "いじょう", meanings: ["abnormal", "unusual", "extraordinary"] },
  "笑い": { word: "笑い", reading: "わらい", meanings: ["laugh", "laughter", "smile"] },
  "硬貨": { word: "硬貨", reading: "こうか", meanings: ["coin", "hard currency", "Coin"] },
  "位置": { word: "位置", reading: "いち", meanings: ["place", "position", "location"] },
  "舌": { word: "舌", reading: "した", meanings: ["tongue", "tongue-like object", "clapper (of a bell)"] },
  "監督": { word: "監督", reading: "かんとく", meanings: ["supervision", "control", "superintendence"] },
  "針": { word: "針", reading: "はり", meanings: ["needle", "pin", "hook"] },
  "予算": { word: "予算", reading: "よさん", meanings: ["estimate (of costs)", "budget", "Budget"] },
  "感覚": { word: "感覚", reading: "かんかく", meanings: ["sense", "sensation", "feeling"] },
  "瞬間": { word: "瞬間", reading: "しゅんかん", meanings: ["moment", "instant", "second"] },
  "速度": { word: "速度", reading: "そくど", meanings: ["speed", "velocity", "pace"] },
  "対象": { word: "対象", reading: "たいしょう", meanings: ["target", "object (of worship, study, etc.)", "subject (of taxation, etc.)"] },
  "酸素": { word: "酸素", reading: "さんそ", meanings: ["oxygen (O)", "Oxygen"] },
  "絶滅": { word: "絶滅", reading: "ぜつめつ", meanings: ["extinction", "extermination", "eradication"] },
  "穀物": { word: "穀物", reading: "こくもつ", meanings: ["grain", "cereal", "corn"] },
  "拍手": { word: "拍手", reading: "はくしゅ", meanings: ["clapping hands", "applause", "clapping one's hands in prayer (at a shrine)"] },
  "祭り": { word: "祭り", reading: "まつり", meanings: ["festival", "feast", "matsuri"] },
  "腰": { word: "腰", reading: "こし", meanings: ["lower back", "waist", "hips"] },
  "奨学金": { word: "奨学金", reading: "しょうがくきん", meanings: ["scholarship", "stipend", "bursary"] },
  "物質": { word: "物質", reading: "ぶっしつ", meanings: ["material", "substance", "matter"] },
  "農家": { word: "農家", reading: "のうか", meanings: ["farmer", "farming family", "farmhouse"] },
  "泥": { word: "泥", reading: "どろ", meanings: ["mud", "(wet) dirt", "thief"] },
  "巣": { word: "巣", reading: "す", meanings: ["nest", "rookery", "breeding place"] },
  "批評": { word: "批評", reading: "ひひょう", meanings: ["criticism", "critique", "review"] },
  "黒板": { word: "黒板", reading: "こくばん", meanings: ["blackboard", "Chalkboard"] },
  "安定": { word: "安定", reading: "あんてい", meanings: ["stability", "steadiness", "consistency"] },
  "議会": { word: "議会", reading: "ぎかい", meanings: ["congress", "parliament", "diet"] },
  "石炭": { word: "石炭", reading: "せきたん", meanings: ["coal", "Coal"] },
  "農業": { word: "農業", reading: "のうぎょう", meanings: ["agriculture", "farming", "Agriculture"] },
  "独身": { word: "独身", reading: "どくしん", meanings: ["unmarried", "single", "Single person"] },
  "吸収": { word: "吸収", reading: "きゅうしゅう", meanings: ["absorption", "suction", "attraction"] },
  "活用": { word: "活用", reading: "かつよう", meanings: ["practical use", "application", "making good use of"] },
  "文明": { word: "文明", reading: "ぶんめい", meanings: ["civilization", "civilisation", "culture"] },
  "日付": { word: "日付", reading: "ひづけ", meanings: ["date", "dating", "Calendar date"] },
  "体温": { word: "体温", reading: "たいおん", meanings: ["body temperature", "Human body temperature"] },
  "知事": { word: "知事", reading: "ちじ", meanings: ["prefectural governor", "Governor"] },
  "大陸": { word: "大陸", reading: "たいりく", meanings: ["continent", "continental Asia (esp. mainland China)", "continental Europe"] },
  "建築": { word: "建築", reading: "けんちく", meanings: ["construction", "architecture (of buildings)", "Architecture"] },
  "金融": { word: "金融", reading: "きんゆう", meanings: ["finance", "financing", "credit transacting"] },
  "信仰": { word: "信仰", reading: "しんこう", meanings: ["(religious) faith", "belief", "creed"] },
  "翼": { word: "翼", reading: "つばさ", meanings: ["wing", "Chinese \"Wings\" constellation (one of the 28 mansions)", "counter for birds or bird wings"] },
  "学期": { word: "学期", reading: "がっき", meanings: ["school term", "semester", "Academic term"] },
  "大臣": { word: "大臣", reading: "だいじん", meanings: ["cabinet minister", "Minister (government)"] },
  "外交": { word: "外交", reading: "がいこう", meanings: ["diplomacy", "selling (e.g. door-to-door)", "canvassing"] },
  "居間": { word: "居間", reading: "いま", meanings: ["living room (Western style)", "sitting room", "Living room"] },
  "理想": { word: "理想", reading: "りそう", meanings: ["ideal", "ideals", "Ideal (ethics)"] },
  "筋肉": { word: "筋肉", reading: "きんにく", meanings: ["muscle", "Muscle"] },
  "現状": { word: "現状", reading: "げんじょう", meanings: ["present condition", "existing state", "status quo"] },
  "助手": { word: "助手", reading: "じょしゅ", meanings: ["assistant", "helper", "assistant (to a professor)"] },
  "神経": { word: "神経", reading: "しんけい", meanings: ["nerve", "nerves", "sensitivity"] },
  "絵画": { word: "絵画", reading: "かいが", meanings: ["painting", "picture", "Painting"] },
  "人種": { word: "人種", reading: "じんしゅ", meanings: ["race (of people)", "type of person", "Race (human classification)"] },
  "鍋": { word: "鍋", reading: "なべ", meanings: ["pan", "pot", "saucepan"] },
  "営業": { word: "営業", reading: "えいぎょう", meanings: ["business", "trade", "operations"] },
  "火災": { word: "火災", reading: "かさい", meanings: ["conflagration", "fire", "Conflagration"] },
  "悪魔": { word: "悪魔", reading: "あくま", meanings: ["devil", "demon", "fiend"] },
  "金庫": { word: "金庫", reading: "きんこ", meanings: ["safe", "strongbox", "cashbox"] },
  "腹": { word: "腹", reading: "はら", meanings: ["abdomen", "belly", "stomach"] },
  "組合": { word: "組合", reading: "くみあい", meanings: ["association", "union", "guild"] },
  "伝統": { word: "伝統", reading: "でんとう", meanings: ["tradition", "convention", "Tradition"] },
  "板": { word: "板", reading: "いた", meanings: ["board", "plank", "sheet (of metal)"] },
  "現象": { word: "現象", reading: "げんしょう", meanings: ["phenomenon", "Phenomenon"] },
  "宝": { word: "宝", reading: "たから", meanings: ["treasure", "Treasure"] },
  "食品": { word: "食品", reading: "しょくひん", meanings: ["food", "food products", "foodstuffs"] },
  "旗": { word: "旗", reading: "はた", meanings: ["flag", "pataka (banner)", "banner (administrative division of Inner Mongolia)"] },
  "資源": { word: "資源", reading: "しげん", meanings: ["resources", "Resource"] },
  "恋人": { word: "恋人", reading: "こいびと", meanings: ["lover", "sweetheart", "boyfriend"] },
  "岸": { word: "岸", reading: "きし", meanings: ["bank", "coast", "shore"] },
  "哲学": { word: "哲学", reading: "てつがく", meanings: ["philosophy", "Philosophy"] },
  "呼吸": { word: "呼吸", reading: "こきゅう", meanings: ["breathing", "respiration", "knack"] },
  "炎": { word: "炎", reading: "ほのお", meanings: ["flame", "blaze", "flames (of intense emotion, e.g. love, jealousy, anger)"] },
  "跡": { word: "跡", reading: "あと", meanings: ["trace", "tracks", "mark"] },
  "温度": { word: "温度", reading: "おんど", meanings: ["temperature", "Temperature"] },
  "鬼": { word: "鬼", reading: "おに", meanings: ["ogre", "demon", "oni"] },
  "知能": { word: "知能", reading: "ちのう", meanings: ["intelligence", "intellect", "brains"] },
  "登山": { word: "登山", reading: "とざん", meanings: ["mountain climbing", "mountaineering", "ascent of a mountain"] },
  "骨折": { word: "骨折", reading: "こっせつ", meanings: ["bone fracture", "Bone fracture"] },
  "代理": { word: "代理", reading: "だいり", meanings: ["representation", "agency", "proxy"] },
  "憲法": { word: "憲法", reading: "けんぽう", meanings: ["constitution", "rules", "regulation"] },
  "印刷": { word: "印刷", reading: "いんさつ", meanings: ["printing", "Printing"] },
  "弁当": { word: "弁当", reading: "べんとう", meanings: ["bento", "Japanese box lunch", "Bento"] },
  "相続": { word: "相続", reading: "そうぞく", meanings: ["succession", "inheritance", "Inheritance"] },
  "銀": { word: "銀", reading: "ぎん", meanings: ["silver (Ag)", "silver (color)", "silver (medal, prize, etc.)"] },
  "大使": { word: "大使", reading: "たいし", meanings: ["ambassador", "Ambassador"] },
  "航空": { word: "航空", reading: "こうくう", meanings: ["aviation", "flying", "Aviation"] },
  "渋滞": { word: "渋滞", reading: "じゅうたい", meanings: ["(traffic) congestion", "traffic jam", "gridlock"] },
  "歩道": { word: "歩道", reading: "ほどう", meanings: ["footpath", "walkway", "sidewalk"] },
  "芽": { word: "芽", reading: "め", meanings: ["sprout", "shoot", "bud"] },
  "免許": { word: "免許", reading: "めんきょ", meanings: ["license", "licence", "permission"] },
  "医療": { word: "医療", reading: "いりょう", meanings: ["medical treatment", "medical care", "Health care"] },
  "衛星": { word: "衛星", reading: "えいせい", meanings: ["(natural) satellite", "moon", "(artificial) satellite"] },
  "栄養": { word: "栄養", reading: "えいよう", meanings: ["nutrition", "nourishment", "Nutrition"] },
  "模様": { word: "模様", reading: "もよう", meanings: ["pattern", "figure", "design"] },
  "会計": { word: "会計", reading: "かいけい", meanings: ["accounting", "finance", "account"] },
  "議員": { word: "議員", reading: "ぎいん", meanings: ["member of an assembly", "member of the Diet", "member of parliament"] },
  "地下": { word: "地下", reading: "ちか", meanings: ["underground", "below the ground", "world of the dead"] },
  "道徳": { word: "道徳", reading: "どうとく", meanings: ["morals", "morality", "Morality"] },
  "筋": { word: "筋", reading: "すじ", meanings: ["muscle", "tendon", "sinew"] },
  "笛": { word: "笛", reading: "ふえ", meanings: ["flute", "fife", "pipe"] },
  "差別": { word: "差別", reading: "さべつ", meanings: ["distinction", "differentiation", "discrimination"] },
  "湾": { word: "湾", reading: "わん", meanings: ["bay", "gulf", "inlet"] },
  "資本": { word: "資本", reading: "しほん", meanings: ["funds", "capital", "Capital (economics)"] },
  "国語": { word: "国語", reading: "こくご", meanings: ["national language", "Japanese language (esp. as a school subject in Japan)", "one's native language"] },
  "礼": { word: "礼", reading: "れい", meanings: ["thanks", "gratitude", "manners"] },
  "豆": { word: "豆", reading: "まめ", meanings: ["legume (esp. edible legumes or their seeds, e.g. beans, peas, pulses)", "bean", "pea"] },
  "体育": { word: "体育", reading: "たいいく", meanings: ["physical education", "PE", "gym (class)"] },
  "筆": { word: "筆", reading: "ふで", meanings: ["writing brush", "paintbrush", "pen"] },
  "作曲": { word: "作曲", reading: "さっきょく", meanings: ["composition (of music)", "setting", "writing music"] },
  "句": { word: "句", reading: "く", meanings: ["section (i.e. of text)", "sentence", "passage"] },
  "茶": { word: "茶", reading: "ちゃ", meanings: ["tea", "tea plant (Camellia sinensis)", "tea preparation"] },
  "刀": { word: "刀", reading: "かたな", meanings: ["sword (esp. Japanese single-edged)", "katana", "scalpel"] },
  "土産": { word: "土産", reading: "みやげ", meanings: ["local specialty or souvenir bought as a gift while travelling", "present brought by a visitor", "something unpleasant that one is given (e.g. an illness while on vacation)"] },
  "粉": { word: "粉", reading: "こな", meanings: ["flour", "meal", "powder"] },
  "熱帯": { word: "熱帯", reading: "ねったい", meanings: ["tropics", "Tropics"] },
  "泡": { word: "泡", reading: "あわ", meanings: ["bubble", "foam", "froth"] },
  "電子": { word: "電子", reading: "でんし", meanings: ["electron", "electronic", "Electron"] },
  "飯": { word: "飯", reading: "めし", meanings: ["cooked rice", "meal", "food"] },
  "梅": { word: "梅", reading: "うめ", meanings: ["Japanese apricot (Prunus mume)", "Japanese plum", "ume"] },
  "能": { word: "能", reading: "のう", meanings: ["talent", "gift", "function"] },
  "儀式": { word: "儀式", reading: "ぎしき", meanings: ["ceremony", "rite", "ritual"] },
  "南極": { word: "南極", reading: "なんきょく", meanings: ["South Pole", "the Antarctic", "Antarctica"] },
  "職人": { word: "職人", reading: "しょくにん", meanings: ["craftsman", "artisan", "tradesman"] },
  "北極": { word: "北極", reading: "ほっきょく", meanings: ["North Pole", "the Arctic", "Hokkyoku"] },
  "新幹線": { word: "新幹線", reading: "しんかんせん", meanings: ["Shinkansen", "bullet train", "Shinkansen"] },
  "昼寝": { word: "昼寝", reading: "ひるね", meanings: ["(afternoon) nap", "sleeping during the day", "siesta"] },
  "木材": { word: "木材", reading: "もくざい", meanings: ["lumber", "timber", "wood"] },
  "大通り": { word: "大通り", reading: "おおどおり", meanings: ["main street", "avenue", "boulevard"] },
  "運河": { word: "運河", reading: "うんが", meanings: ["(navigable) canal", "waterway", "Unga"] },
  "遊園地": { word: "遊園地", reading: "ゆうえんち", meanings: ["amusement park", "Yuuenchi", "Amusement park"] },
  "蛇口": { word: "蛇口", reading: "じゃぐち", meanings: ["faucet", "tap", "Jaguchi"] },
  "天皇": { word: "天皇", reading: "てんのう", meanings: ["Emperor of Japan", "Tennou", "Emperor of Japan"] },
  "溶岩": { word: "溶岩", reading: "ようがん", meanings: ["lava", "Yougan", "Lava"] },
  "武士": { word: "武士", reading: "ぶし", meanings: ["samurai", "warrior", "Mononofu"] },
  "月": { word: "月", reading: "つき", meanings: ["Moon", "month", "moonlight"] },
  "馬鹿": { word: "馬鹿", reading: "ばか", meanings: ["idiot", "moron", "fool"] },
  "屡々": { word: "屡々", reading: "しばしば", meanings: ["often", "again and again", "frequently"] },
  "退屈": { word: "退屈", reading: "たいくつ", meanings: ["tedious", "boring", "dull"] },
  "流れる": { word: "流れる", reading: "ながれる", meanings: ["to stream", "to flow (liquid, time, etc.)", "to run (ink)"] },
  "暗記": { word: "暗記", reading: "あんき", meanings: ["memorization", "memorisation", "learning by heart"] },
  "兎": { word: "兎", reading: "うさぎ", meanings: ["rabbit", "hare", "coney"] },
  "ネズミ": { word: "ネズミ", reading: "ネズミ", meanings: ["mouse", "rat", "dark gray"] },
  "頬": { word: "頬", reading: "ほお", meanings: ["cheek (of the face)", "Cheek"] },
  "膝": { word: "膝", reading: "ひざ", meanings: ["knee", "lap", "knee and thigh (while sitting)"] },
  "餌": { word: "餌", reading: "えさ", meanings: ["(animal) feed", "fodder", "pet food"] },
  "量": { word: "量", reading: "りょう", meanings: ["quantity", "amount", "volume"] },
  "莫大": { word: "莫大", reading: "ばくだい", meanings: ["vast", "huge", "immense"] },
  "式": { word: "式", reading: "しき", meanings: ["way", "style", "fashion"] },
  "紐": { word: "紐", reading: "ひも", meanings: ["string", "cord", "leash"] },
  "連想": { word: "連想", reading: "れんそう", meanings: ["association (of ideas)", "being reminded (of something)", "suggestion"] },
  "地平線": { word: "地平線", reading: "ちへいせん", meanings: ["horizon (related to land)", "Horizon"] },
  "場": { word: "場", reading: "ば", meanings: ["place", "spot", "space"] },
  "袖": { word: "袖", reading: "そで", meanings: ["sleeve", "wing (of a stage, desk, gate, etc.)", "flap (of a dust jacket)"] },
  "動詞": { word: "動詞", reading: "どうし", meanings: ["verb", "Verb"] },
  "灰": { word: "灰", reading: "はい", meanings: ["ash", "ashes", "Ash (analytical chemistry)"] },
  "秒": { word: "秒", reading: "びょう", meanings: ["second (unit of time)", "arc second", "Second"] },
  "県": { word: "県", reading: "けん", meanings: ["prefecture (of Japan)", "county (of China, Taiwan, Norway, etc.)", "department (of France)"] },
  "帯": { word: "帯", reading: "おび", meanings: ["obi (kimono sash)", "obi (strip of paper looped around a book, CD, etc. containing information about the product)", "band"] },
  "苗字": { word: "苗字", reading: "みょうじ", meanings: ["surname", "family name", "last name"] },
  "有る": { word: "有る", reading: "ある", meanings: ["to be", "to exist", "to live"] },
  "其の": { word: "其の", reading: "その", meanings: ["that", "the", "part (as in \"part two\")"] },
  "言う": { word: "言う", reading: "いう", meanings: ["to say", "to utter", "to declare"] },
  "出来る": { word: "出来る", reading: "できる", meanings: ["to be able to do", "to be possible", "to be permitted (to do)"] },
  "良い": { word: "良い", reading: "よい", meanings: ["good", "excellent", "fine"] },
  "下さい": { word: "下さい", reading: "ください", meanings: ["please (give me)", "please (do for me)"] },
  "見る": { word: "見る", reading: "みる", meanings: ["to see", "to look", "to watch"] },
  "此の": { word: "此の", reading: "この", meanings: ["this", "last (couple of years, etc.)", "these"] },
  "自分": { word: "自分", reading: "じぶん", meanings: ["myself", "yourself", "oneself"] },
  "知る": { word: "知る", reading: "しる", meanings: ["to know", "to be aware (of)", "to be conscious (of)"] },
  "持つ": { word: "持つ", reading: "もつ", meanings: ["to hold (in one's hand)", "to take", "to carry"] },
  "何": { word: "何", reading: "なに", meanings: ["what", "you-know-what", "that thing"] },
  "車": { word: "車", reading: "くるま", meanings: ["car", "automobile", "vehicle"] },
  "話す": { word: "話す", reading: "はなす", meanings: ["to talk", "to speak", "to converse"] },
  "今": { word: "今", reading: "いま", meanings: ["now", "the present time", "just now"] },
  "今日": { word: "今日", reading: "きょう", meanings: ["today", "this day", "these days"] },
  "買う": { word: "買う", reading: "かう", meanings: ["to buy", "to purchase", "to value (highly)"] },
  "読む": { word: "読む", reading: "よむ", meanings: ["to read", "to recite (e.g. a sutra)", "to chant"] },
  "皆": { word: "皆", reading: "みな", meanings: ["everyone", "everybody", "all"] },
  "新しい": { word: "新しい", reading: "あたらしい", meanings: ["new", "novel", "fresh"] },
  "話": { word: "話", reading: "はなし", meanings: ["talk", "speech", "chat"] },
  "明日": { word: "明日", reading: "あした", meanings: ["tomorrow", "near future"] },
  "昨日": { word: "昨日", reading: "きのう", meanings: ["yesterday"] },
  "出る": { word: "出る", reading: "でる", meanings: ["to leave", "to exit", "to go out"] },
  "勉強": { word: "勉強", reading: "べんきょう", meanings: ["study", "diligence", "working hard"] },
  "取る": { word: "取る", reading: "とる", meanings: ["to take", "to pick up", "to grab"] },
  "誰": { word: "誰", reading: "だれ", meanings: ["who"] },
  "お金": { word: "お金", reading: "おかね", meanings: ["money"] },
  "男": { word: "男", reading: "おとこ", meanings: ["man", "male", "fellow"] },
  "犬": { word: "犬", reading: "いぬ", meanings: ["dog (Canis (lupus) familiaris)", "canine", "squealer"] },
  "使う": { word: "使う", reading: "つかう", meanings: ["to use (a tool, method, etc.)", "to make use of", "to put to use"] },
  "大変": { word: "大変", reading: "たいへん", meanings: ["very", "greatly", "terribly"] },
  "待つ": { word: "待つ", reading: "まつ", meanings: ["to wait", "to await", "to look forward to"] },
  "作る": { word: "作る", reading: "つくる", meanings: ["to make", "to produce", "to manufacture"] },
  "後ろ": { word: "後ろ", reading: "うしろ", meanings: ["back", "behind", "rear"] },
  "町": { word: "町", reading: "まち", meanings: ["town", "block", "neighbourhood"] },
  "駅": { word: "駅", reading: "えき", meanings: ["railway station", "train station", "staging post on a highway (in pre-modern Japan)"] },
  "少し": { word: "少し", reading: "すこし", meanings: ["a little", "a bit", "a small amount"] },
  "貴方": { word: "貴方", reading: "あなた", meanings: ["you", "dear", "honey"] },
  "欲しい": { word: "欲しい", reading: "ほしい", meanings: ["wanting (to have)", "desiring", "wishing for"] },
  "行く": { word: "行く", reading: "いく", meanings: ["to go", "to move (towards)", "to head (towards)"] },
  "乗る": { word: "乗る", reading: "のる", meanings: ["to get on (train, plane, bus, ship, etc.)", "to get in", "to board"] },
  "大きな": { word: "大きな", reading: "おおきな", meanings: ["big", "large", "great"] },
  "医者": { word: "医者", reading: "いしゃ", meanings: ["doctor", "physician"] },
  "終わる": { word: "終わる", reading: "おわる", meanings: ["to end", "to come to an end", "to finish"] },
  "学生": { word: "学生", reading: "がくせい", meanings: ["student (esp. a university student)"] },
  "長い": { word: "長い", reading: "ながい", meanings: ["long (distance, length)", "long (time)", "protracted"] },
  "何の": { word: "何の", reading: "どの", meanings: ["which", "what (way)"] },
  "又": { word: "又", reading: "また", meanings: ["again", "once more", "once again"] },
  "国": { word: "国", reading: "くに", meanings: ["country", "state", "region"] },
  "高い": { word: "高い", reading: "たかい", meanings: ["high", "tall", "expensive"] },
  "余り": { word: "余り", reading: "あまり", meanings: ["remainder", "remnant", "rest"] },
  "難しい": { word: "難しい", reading: "むずかしい", meanings: ["difficult", "hard", "troublesome"] },
  "友達": { word: "友達", reading: "ともだち", meanings: ["friend", "companion"] },
  "本当": { word: "本当", reading: "ほんとう", meanings: ["truth", "reality", "actuality"] },
  "寝る": { word: "寝る", reading: "ねる", meanings: ["to sleep (lying down)", "to go to bed", "to lie in bed"] },
  "生徒": { word: "生徒", reading: "せいと", meanings: ["pupil", "student", "schoolchild"] },
  "忙しい": { word: "忙しい", reading: "いそがしい", meanings: ["busy", "occupied", "hectic"] },
  "両親": { word: "両親", reading: "りょうしん", meanings: ["parents", "both parents"] },
  "泳ぐ": { word: "泳ぐ", reading: "およぐ", meanings: ["to swim", "to struggle through (a crowd)", "to make one's way through the world"] },
  "立つ": { word: "立つ", reading: "たつ", meanings: ["to stand (up)", "to rise", "to get to one's feet"] },
  "出す": { word: "出す", reading: "だす", meanings: ["to take out", "to get out", "to put out"] },
  "早い": { word: "早い", reading: "はやい", meanings: ["fast", "quick", "rapid"] },
  "楽しい": { word: "楽しい", reading: "たのしい", meanings: ["enjoyable", "fun", "pleasant"] },
  "面白い": { word: "面白い", reading: "おもしろい", meanings: ["interesting", "fascinating", "intriguing"] },
  "絵": { word: "絵", reading: "え", meanings: ["picture", "drawing", "painting"] },
  "女の子": { word: "女の子", reading: "おんなのこ", meanings: ["girl", "daughter", "baby girl"] },
  "着る": { word: "着る", reading: "きる", meanings: ["to wear (from the shoulders down)", "to put on", "to take (the blame, responsibility)"] },
  "上手": { word: "上手", reading: "じょうず", meanings: ["skillful", "skilled", "proficient"] },
  "古い": { word: "古い", reading: "ふるい", meanings: ["old", "aged", "ancient"] },
  "強い": { word: "強い", reading: "つよい", meanings: ["strong", "potent", "competent"] },
  "全部": { word: "全部", reading: "ぜんぶ", meanings: ["all", "entire", "whole"] },
  "呼ぶ": { word: "呼ぶ", reading: "よぶ", meanings: ["to call out (to)", "to call", "to invoke"] },
  "午後": { word: "午後", reading: "ごご", meanings: ["afternoon", "p.m."] },
  "掛ける": { word: "掛ける", reading: "かける", meanings: ["to hang up (e.g. a coat, a picture on the wall)", "to let hang", "to suspend (from)"] },
  "辞書": { word: "辞書", reading: "じしょ", meanings: ["dictionary", "lexicon", "letter of resignation"] },
  "天気": { word: "天気", reading: "てんき", meanings: ["weather", "fair weather", "fine weather"] },
  "体": { word: "体", reading: "からだ", meanings: ["body", "torso", "trunk"] },
  "大きい": { word: "大きい", reading: "おおきい", meanings: ["big", "large", "great"] },
  "質問": { word: "質問", reading: "しつもん", meanings: ["question", "inquiry", "enquiry"] },
  "昨夜": { word: "昨夜", reading: "ゆうべ", meanings: ["last night", "yesterday evening"] },
  "有名": { word: "有名", reading: "ゆうめい", meanings: ["famous", "well-known"] },
  "兄": { word: "兄", reading: "あに", meanings: ["older brother", "elder brother", "brother-in-law (spouse's older brother or older sister's husband)"] },
  "歌う": { word: "歌う", reading: "うたう", meanings: ["to sing", "to sing of (love, beauty, etc.) in a poem", "to express in the form of a poem"] },
  "上る": { word: "上る", reading: "のぼる", meanings: ["to ascend", "to go up", "to climb"] },
  "服": { word: "服", reading: "ふく", meanings: ["clothes (esp. Western clothes)", "clothing", "dress"] },
  "鳥": { word: "鳥", reading: "とり", meanings: ["bird", "bird meat (esp. chicken meat)", "fowl"] },
  "時々": { word: "時々", reading: "ときどき", meanings: ["sometimes", "occasionally", "at times"] },
  "妹": { word: "妹", reading: "いもうと", meanings: ["younger sister"] },
  "二つ": { word: "二つ", reading: "ふたつ", meanings: ["two"] },
  "頼む": { word: "頼む", reading: "たのむ", meanings: ["to request", "to beg", "to ask"] },
  "お父さん": { word: "お父さん", reading: "おとうさん", meanings: ["father", "dad", "papa"] },
  "今朝": { word: "今朝", reading: "けさ", meanings: ["this morning"] },
  "遅い": { word: "遅い", reading: "おそい", meanings: ["slow", "late", "too late"] },
  "借りる": { word: "借りる", reading: "かりる", meanings: ["to borrow", "to rent", "to hire"] },
  "薬": { word: "薬", reading: "くすり", meanings: ["medicine", "pharmaceuticals", "(legal) drugs"] },
  "庭": { word: "庭", reading: "にわ", meanings: ["garden", "yard", "courtyard"] },
  "外国": { word: "外国", reading: "がいこく", meanings: ["foreign country"] },
  "元気": { word: "元気", reading: "げんき", meanings: ["lively", "full of spirit", "energetic"] },
  "小さい": { word: "小さい", reading: "ちいさい", meanings: ["small", "little", "tiny"] },
  "弟": { word: "弟", reading: "おとうと", meanings: ["younger brother", "little brother", "kid brother"] },
  "魚": { word: "魚", reading: "さかな", meanings: ["fish"] },
  "今年": { word: "今年", reading: "ことし", meanings: ["this year"] },
  "お母さん": { word: "お母さん", reading: "おかあさん", meanings: ["mother", "mom", "mum"] },
  "男の子": { word: "男の子", reading: "おとこのこ", meanings: ["boy", "son", "baby boy"] },
  "飛ぶ": { word: "飛ぶ", reading: "とぶ", meanings: ["to fly", "to soar", "to jump"] },
  "売る": { word: "売る", reading: "うる", meanings: ["to sell", "to betray", "to sell out (one's friend, country, etc.)"] },
  "静か": { word: "静か", reading: "しずか", meanings: ["quiet", "silent", "slow"] },
  "休む": { word: "休む", reading: "やすむ", meanings: ["to be absent", "to take a day off", "to rest"] },
  "食べ物": { word: "食べ物", reading: "たべもの", meanings: ["food"] },
  "大切": { word: "大切", reading: "たいせつ", meanings: ["important", "significant", "serious"] },
  "警官": { word: "警官", reading: "けいかん", meanings: ["police officer", "policeman", "constable"] },
  "来週": { word: "来週", reading: "らいしゅう", meanings: ["next week"] },
  "建物": { word: "建物", reading: "たてもの", meanings: ["building"] },
  "暖かい": { word: "暖かい", reading: "あたたかい", meanings: ["warm", "mild", "(pleasantly) hot"] },
  "降りる": { word: "降りる", reading: "おりる", meanings: ["to descend (e.g. a mountain)", "to go down", "to come down"] },
  "止まる": { word: "止まる", reading: "とまる", meanings: ["to stop (moving)", "to come to a stop", "to stop (doing, working, being supplied)"] },
  "一緒": { word: "一緒", reading: "いっしょ", meanings: ["(doing) together", "one lump", "one mixture"] },
  "切り": { word: "切り", reading: "きり", meanings: ["end", "finish", "place to stop"] },
  "先週": { word: "先週", reading: "せんしゅう", meanings: ["last week", "the week before"] },
  "白い": { word: "白い", reading: "しろい", meanings: ["white", "blank (e.g. paper)", "uncolored"] },
  "二": { word: "二", reading: "に", meanings: ["two", "2"] },
  "少ない": { word: "少ない", reading: "すくない", meanings: ["few", "little", "small (amount)"] },
  "赤い": { word: "赤い", reading: "あかい", meanings: ["red", "crimson", "scarlet"] },
  "洗う": { word: "洗う", reading: "あらう", meanings: ["to wash", "to cleanse", "to rinse"] },
  "嫌い": { word: "嫌い", reading: "きらい", meanings: ["disliked", "hated", "disagreeable"] },
  "立派": { word: "立派", reading: "りっぱ", meanings: ["splendid", "fine", "handsome"] },
  "暇": { word: "暇", reading: "ひま", meanings: ["spare time", "free time", "leisure"] },
  "お茶": { word: "お茶", reading: "おちゃ", meanings: ["tea (esp. green or barley)", "tea break", "teatime"] },
  "広い": { word: "広い", reading: "ひろい", meanings: ["spacious", "vast", "wide"] },
  "去年": { word: "去年", reading: "きょねん", meanings: ["last year"] },
  "隣": { word: "隣", reading: "となり", meanings: ["next (to)", "adjoining", "adjacent"] },
  "大好き": { word: "大好き", reading: "だいすき", meanings: ["liking very much", "loving (something or someone)", "adoring"] },
  "女": { word: "女", reading: "おんな", meanings: ["woman", "female", "female lover"] },
  "切る": { word: "切る", reading: "きる", meanings: ["to cut", "to cut through", "to perform (surgery)"] },
  "多分": { word: "多分", reading: "たぶん", meanings: ["probably", "likely", "perhaps"] },
  "嫌": { word: "嫌", reading: "いや", meanings: ["disliking", "not wanting", "unwilling (to do)"] },
  "毎朝": { word: "毎朝", reading: "まいあさ", meanings: ["every morning"] },
  "荷物": { word: "荷物", reading: "にもつ", meanings: ["luggage", "baggage", "package"] },
  "番号": { word: "番号", reading: "ばんごう", meanings: ["number", "series of digits"] },
  "返す": { word: "返す", reading: "かえす", meanings: ["to return (something)", "to restore", "to put back"] },
  "来年": { word: "来年", reading: "らいねん", meanings: ["next year"] },
  "明るい": { word: "明るい", reading: "あかるい", meanings: ["light", "bright", "well-lit"] },
  "近い": { word: "近い", reading: "ちかい", meanings: ["near", "close", "short (distance)"] },
  "向こう": { word: "向こう", reading: "むこう", meanings: ["opposite side", "other side", "over there"] },
  "始め": { word: "始め", reading: "はじめ", meanings: ["beginning", "start", "outset"] },
  "痛い": { word: "痛い", reading: "いたい", meanings: ["painful", "sore", "cringy"] },
  "秋": { word: "秋", reading: "あき", meanings: ["autumn", "fall"] },
  "休み": { word: "休み", reading: "やすみ", meanings: ["rest", "recess", "respite"] },
  "練習": { word: "練習", reading: "れんしゅう", meanings: ["practice", "training", "drill"] },
  "十": { word: "十", reading: "じゅう", meanings: ["ten", "10", "ten years of age"] },
  "上着": { word: "上着", reading: "うわぎ", meanings: ["coat", "jacket", "outerwear"] },
  "先月": { word: "先月", reading: "せんげつ", meanings: ["last month"] },
  "結構": { word: "結構", reading: "けっこう", meanings: ["splendid", "nice", "wonderful"] },
  "毎年": { word: "毎年", reading: "まいとし", meanings: ["every year", "yearly", "annually"] },
  "兄弟": { word: "兄弟", reading: "きょうだい", meanings: ["brothers and sisters", "siblings", "half-siblings"] },
  "来月": { word: "来月", reading: "らいげつ", meanings: ["next month"] },
  "五": { word: "五", reading: "ご", meanings: ["five", "5"] },
  "飲み物": { word: "飲み物", reading: "のみもの", meanings: ["drink", "beverage"] },
  "弱い": { word: "弱い", reading: "よわい", meanings: ["weak", "frail", "delicate"] },
  "牛乳": { word: "牛乳", reading: "ぎゅうにゅう", meanings: ["(cow's) milk"] },
  "三": { word: "三", reading: "さん", meanings: ["three", "3"] },
  "大丈夫": { word: "大丈夫", reading: "だいじょうぶ", meanings: ["safe", "secure", "sound"] },
  "黒い": { word: "黒い", reading: "くろい", meanings: ["black", "dark", "blackish"] },
  "皆さん": { word: "皆さん", reading: "みなさん", meanings: ["all", "everyone", "everybody"] },
  "半分": { word: "半分", reading: "はんぶん", meanings: ["half"] },
  "押す": { word: "押す", reading: "おす", meanings: ["to push", "to thrust", "to shove"] },
  "勤める": { word: "勤める", reading: "つとめる", meanings: ["to work (for)", "to be employed (at)", "to serve (in)"] },
  "熱い": { word: "熱い", reading: "あつい", meanings: ["hot (to the touch)", "passionate (feelings, etc.)", "ardent"] },
  "三つ": { word: "三つ", reading: "みっつ", meanings: ["three", "three years of age"] },
  "果物": { word: "果物", reading: "くだもの", meanings: ["fruit"] },
  "今週": { word: "今週", reading: "こんしゅう", meanings: ["this week"] },
  "甘い": { word: "甘い", reading: "あまい", meanings: ["sweet-tasting", "sweet", "sugary"] },
  "右": { word: "右", reading: "みぎ", meanings: ["right", "right-hand side", "right hand"] },
  "晩": { word: "晩", reading: "ばん", meanings: ["evening", "night", "dinner"] },
  "階段": { word: "階段", reading: "かいだん", meanings: ["stairs", "stairway", "staircase"] },
  "幾つ": { word: "幾つ", reading: "いくつ", meanings: ["how many", "how old"] },
  "大勢": { word: "大勢", reading: "おおぜい", meanings: ["crowd of people", "great number of people", "in great numbers"] },
  "張る": { word: "張る", reading: "はる", meanings: ["to stick", "to paste", "to affix"] },
  "夕方": { word: "夕方", reading: "ゆうがた", meanings: ["early evening (usu. from 3pm to 6pm)", "dusk"] },
  "低い": { word: "低い", reading: "ひくい", meanings: ["low (rank, degree, value, content, quality, etc.)", "low (position)", "close to the ground"] },
  "左": { word: "左", reading: "ひだり", meanings: ["left", "left-hand side", "left hand"] },
  "毎週": { word: "毎週", reading: "まいしゅう", meanings: ["every week"] },
  "下手": { word: "下手", reading: "へた", meanings: ["unskillful", "poor", "awkward"] },
  "千": { word: "千", reading: "せん", meanings: ["thousand", "1,000"] },
  "渡す": { word: "渡す", reading: "わたす", meanings: ["to ferry across (e.g. a river)", "to carry across", "to traverse"] },
  "午前": { word: "午前", reading: "ごぜん", meanings: ["morning", "a.m."] },
  "丸い": { word: "丸い", reading: "まるい", meanings: ["round", "circular", "spherical"] },
  "便利": { word: "便利", reading: "べんり", meanings: ["convenient", "handy", "useful"] },
  "今月": { word: "今月", reading: "こんげつ", meanings: ["this month"] },
  "浴びる": { word: "浴びる", reading: "あびる", meanings: ["to dash over oneself (e.g. water)", "to take (e.g. shower)", "to bask in (e.g. the sun)"] },
  "半": { word: "半", reading: "はん", meanings: ["half", "semi-", "partial"] },
  "洋服": { word: "洋服", reading: "ようふく", meanings: ["Western-style clothes (cf. traditional Japanese clothes)"] },
  "撮る": { word: "撮る", reading: "とる", meanings: ["to take (a photograph)", "to record (audio or video)", "to film"] },
  "締める": { word: "締める", reading: "しめる", meanings: ["to tie", "to fasten", "to tighten"] },
  "文章": { word: "文章", reading: "ぶんしょう", meanings: ["writing", "composition", "essay"] },
  "八": { word: "八", reading: "はち", meanings: ["eight", "8"] },
  "薄い": { word: "薄い", reading: "うすい", meanings: ["thin (of an object)", "pale", "light"] },
  "横": { word: "横", reading: "よこ", meanings: ["horizontal (as opposed to vertical)", "side-to-side (as opposed to front-to-back)", "width"] },
  "四つ": { word: "四つ", reading: "よっつ", meanings: ["four", "4", "four years of age"] },
  "六": { word: "六", reading: "ろく", meanings: ["six", "6"] },
  "丈夫": { word: "丈夫", reading: "じょうぶ", meanings: ["healthy", "robust", "strong"] },
  "東": { word: "東", reading: "ひがし", meanings: ["east"] },
  "毎晩": { word: "毎晩", reading: "まいばん", meanings: ["every night"] },
  "晴れ": { word: "晴れ", reading: "はれ", meanings: ["clear weather", "fine weather", "formal"] },
  "五つ": { word: "五つ", reading: "いつつ", meanings: ["five", "five years of age", "eight o'clock (old time system)"] },
  "細い": { word: "細い", reading: "ほそい", meanings: ["thin", "slender", "fine"] },
  "廊下": { word: "廊下", reading: "ろうか", meanings: ["corridor", "hallway", "passageway"] },
  "太い": { word: "太い", reading: "ふとい", meanings: ["fat", "thick", "deep (of a voice)"] },
  "縦": { word: "縦", reading: "たて", meanings: ["the vertical", "height", "front-to-back"] },
  "留学生": { word: "留学生", reading: "りゅうがくせい", meanings: ["overseas student", "exchange student"] },
  "九つ": { word: "九つ", reading: "ここのつ", meanings: ["nine", "nine years of age", "twelve o'clock (old time system)"] },
  "七つ": { word: "七つ", reading: "ななつ", meanings: ["seven", "seven years of age", "four o'clock (old time system)"] },
  "一昨年": { word: "一昨年", reading: "おととし", meanings: ["year before last"] },
  "人": { word: "人", reading: "ひと", meanings: ["person", "someone", "somebody"] },
  "居る": { word: "居る", reading: "いる", meanings: ["to be (of animate objects)", "to exist", "to stay"] },
  "其れ": { word: "其れ", reading: "それ", meanings: ["that", "it", "then"] },
  "物": { word: "物", reading: "もの", meanings: ["thing", "object", "article"] },
  "家": { word: "家", reading: "いえ", meanings: ["house", "residence", "dwelling"] },
  "本": { word: "本", reading: "ほん", meanings: ["book", "volume", "script"] },
  "迚も": { word: "迚も", reading: "とても", meanings: ["very", "awfully", "exceedingly"] },
  "会う": { word: "会う", reading: "あう", meanings: ["to meet", "to encounter", "to see"] },
  "好き": { word: "好き", reading: "すき", meanings: ["liking", "being fond of", "to one's liking"] },
  "分かる": { word: "分かる", reading: "わかる", meanings: ["to understand", "to comprehend", "to grasp"] },
  "此れ": { word: "此れ", reading: "これ", meanings: ["this", "this one", "this person"] },
  "聞く": { word: "聞く", reading: "きく", meanings: ["to hear", "to listen (e.g. to music)", "to ask"] },
  "所": { word: "所", reading: "ところ", meanings: ["place", "spot", "scene"] },
  "先": { word: "先", reading: "さき", meanings: ["point", "tip", "end"] },
  "何時も": { word: "何時も", reading: "いつも", meanings: ["always", "all the time", "at all times"] },
  "書く": { word: "書く", reading: "かく", meanings: ["to write", "to compose", "to pen"] },
  "沢山": { word: "沢山", reading: "たくさん", meanings: ["a lot", "lots", "plenty"] },
  "入る": { word: "入る", reading: "はいる", meanings: ["to enter", "to come in", "to go in"] },
  "置く": { word: "置く", reading: "おく", meanings: ["to put", "to place", "to leave (behind)"] },
  "何処": { word: "何処", reading: "どこ", meanings: ["where", "what place", "how much (long, far)"] },
  "住む": { word: "住む", reading: "すむ", meanings: ["to live (of humans)", "to reside", "to inhabit"] },
  "食べる": { word: "食べる", reading: "たべる", meanings: ["to eat", "to live on (e.g. a salary)", "to live off"] },
  "歩く": { word: "歩く", reading: "あるく", meanings: ["to walk"] },
  "働く": { word: "働く", reading: "はたらく", meanings: ["to work", "to labor", "to labour"] },
  "着く": { word: "着く", reading: "つく", meanings: ["to arrive at", "to reach", "to sit on"] },
  "上": { word: "上", reading: "うえ", meanings: ["above", "over", "up"] },
  "悪い": { word: "悪い", reading: "わるい", meanings: ["bad", "poor", "undesirable"] },
  "教える": { word: "教える", reading: "おしえる", meanings: ["to teach", "to instruct", "to tell"] },
  "降る": { word: "降る", reading: "ふる", meanings: ["to fall (of rain, snow, ash, etc.)", "to come down", "to form (of frost)"] },
  "死ぬ": { word: "死ぬ", reading: "しぬ", meanings: ["to die", "to pass away", "to lose spirit"] },
  "帰る": { word: "帰る", reading: "かえる", meanings: ["to return", "to come home", "to go home"] },
  "多い": { word: "多い", reading: "おおい", meanings: ["many", "numerous", "a lot"] },
  "出かける": { word: "出かける", reading: "でかける", meanings: ["to go out (e.g. on an excursion or outing)", "to leave", "to depart"] },
  "若い": { word: "若い", reading: "わかい", meanings: ["young", "youthful", "immature"] },
  "掛かる": { word: "掛かる", reading: "かかる", meanings: ["to take (a resource, e.g. time or money)", "to hang", "to come into view"] },
  "同じ": { word: "同じ", reading: "おなじ", meanings: ["same", "identical", "equal"] },
  "起きる": { word: "起きる", reading: "おきる", meanings: ["to get up", "to rise", "to blaze up (fire)"] },
  "座る": { word: "座る", reading: "すわる", meanings: ["to sit (down)", "to have a seat", "to be seated"] },
  "店": { word: "店", reading: "みせ", meanings: ["store", "shop", "establishment"] },
  "入れる": { word: "入れる", reading: "いれる", meanings: ["to put in", "to let in", "to take in"] },
  "何方": { word: "何方", reading: "どなた", meanings: ["who"] },
  "一寸": { word: "一寸", reading: "ちょっと", meanings: ["a little", "a bit", "slightly"] },
  "疲れる": { word: "疲れる", reading: "つかれる", meanings: ["to get tired", "to tire", "to get fatigued"] },
  "開ける": { word: "開ける", reading: "あける", meanings: ["to open (a door, etc.)", "to unwrap (e.g. parcel, package)", "to unlock"] },
  "何故": { word: "何故", reading: "なぜ", meanings: ["why", "how", "for what reason"] },
  "一日": { word: "一日", reading: "いちにち", meanings: ["one day", "all day (long)", "the whole day"] },
  "寒い": { word: "寒い", reading: "さむい", meanings: ["cold (e.g. weather)", "uninteresting (esp. joke)", "lame"] },
  "見せる": { word: "見せる", reading: "みせる", meanings: ["to show", "to display", "to make (something or someone) look ..."] },
  "違う": { word: "違う", reading: "ちがう", meanings: ["to differ (from)", "to be different", "to be distinct"] },
  "如何して": { word: "如何して", reading: "どうして", meanings: ["how", "in what way", "by what means"] },
  "付ける": { word: "付ける", reading: "つける", meanings: ["to attach", "to join", "to connect"] },
  "覚える": { word: "覚える", reading: "おぼえる", meanings: ["to memorize", "to memorise", "to commit to memory"] },
  "風": { word: "風", reading: "かぜ", meanings: ["wind", "breeze", "draught"] },
  "近く": { word: "近く", reading: "ちかく", meanings: ["near", "neighbourhood", "neighborhood"] },
  "困る": { word: "困る", reading: "こまる", meanings: ["to be troubled", "to have difficulty", "to be in a fix"] },
  "生まれる": { word: "生まれる", reading: "うまれる", meanings: ["to be born"] },
  "丁度": { word: "丁度", reading: "ちょうど", meanings: ["exactly", "precisely", "just"] },
  "初めて": { word: "初めて", reading: "はじめて", meanings: ["for the first time", "only after ... is it ...", "only when ... do you ..."] },
  "始まる": { word: "始まる", reading: "はじまる", meanings: ["to begin", "to start", "to commence"] },
  "貸す": { word: "貸す", reading: "かす", meanings: ["to lend", "to loan", "to rent out"] },
  "綺麗": { word: "綺麗", reading: "きれい", meanings: ["pretty", "lovely", "beautiful"] },
  "幾ら": { word: "幾ら", reading: "いくら", meanings: ["how much", "something over", "and something"] },
  "空": { word: "空", reading: "そら", meanings: ["sky", "the air", "the heavens"] },
  "弾く": { word: "弾く", reading: "ひく", meanings: ["to play (a stringed or keyboard instrument)"] },
  "暑い": { word: "暑い", reading: "あつい", meanings: ["hot", "warm", "sultry"] },
  "遊ぶ": { word: "遊ぶ", reading: "あそぶ", meanings: ["to play (games, sports)", "to enjoy oneself", "to have a good time"] },
  "然し": { word: "然し", reading: "しかし", meanings: ["however", "but"] },
  "無くす": { word: "無くす", reading: "なくす", meanings: ["to lose (something)", "to get rid of", "to eliminate"] },
  "色々": { word: "色々", reading: "いろいろ", meanings: ["various", "a variety of", "all sorts of"] },
  "渡る": { word: "渡る", reading: "わたる", meanings: ["to cross over", "to go across", "to extend"] },
  "暗い": { word: "暗い", reading: "くらい", meanings: ["dark", "gloomy", "murky"] },
  "此方": { word: "此方", reading: "こちら", meanings: ["this way", "this direction", "here"] },
  "重い": { word: "重い", reading: "おもい", meanings: ["heavy", "weighty", "heavy (feeling)"] },
  "今晩": { word: "今晩", reading: "こんばん", meanings: ["tonight", "this evening"] },
  "美味しい": { word: "美味しい", reading: "おいしい", meanings: ["good(-tasting)", "nice", "delicious"] },
  "消す": { word: "消す", reading: "けす", meanings: ["to erase", "to rub out", "to rub off"] },
  "易しい": { word: "易しい", reading: "やさしい", meanings: ["easy", "plain", "simple"] },
  "閉める": { word: "閉める", reading: "しめる", meanings: ["to close", "to shut"] },
  "安い": { word: "安い", reading: "やすい", meanings: ["cheap", "inexpensive", "calm"] },
  "遠い": { word: "遠い", reading: "とおい", meanings: ["far", "distant", "far away"] },
};
